title: Garden
views:
  - title: Home
    path: home
    icon: mdi:flower
    layout:
      width: 300
      max_cols: 10
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: group.growlights1
              - entity: input_select.growtent1_growschedule
              - entity: input_datetime.growtent1_lights_on
              - entity: input_datetime.growtent1_lights_off
          - type: custom:mini-graph-card
            entities:
              - sensor.growbot1_illuminance
            align_icon: left
            align_state: center
            show:
              fill: false
          - type: custom:mini-graph-card
            entities:
              - sensor.air_temperature
              - sensor.humidity
              - sensor.soil_temperature
            align_icon: left
            align_state: center
            show:
              fill: false
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: group.growlights2
              - entity: input_select.growtent2_growschedule
              - entity: input_datetime.growtent2_lights_on
              - entity: input_datetime.growtent2_lights_off
          - type: custom:mini-graph-card
            entities:
              - sensor.growbot1_illuminance
            align_icon: left
            align_state: center
            show:
              fill: false
          - type: custom:mini-graph-card
            entities:
              - sensor.air_temperature
              - sensor.humidity
              - sensor.soil_temperature
            align_icon: left
            align_state: center
            show:
              fill: false
