title: Home

custom_header:
  !include custom_header.yaml

decluttering_templates:
  !include_dir_merge_named decluttering_templates/

button_card_templates:
  !include_dir_merge_named button_card_templates/

views:
  - !include views/view_homeassistant.yaml
  - !include views/view_lights.yaml
  - !include views/view_home.yaml
  - !include views/view_sensors.yaml
  - !include views/view_media.yaml
  - title: Devices
    path: devices
    icon: 'mdi:robot-vacuum'
    panel: true
    badges: []
    cards:
      - type: 'custom:layout-card'
        column_width:
          - 375
          - 500
        layout: vertical
        cards:
          - type: 'custom:button-card'
            color: auto
            color_type: blank-card
            styles:
              card:
                - height: 25px
          - type: 'custom:vacuum-card'
            entity: vacuum.xiaomi_vacuum_cleaner
            stats:
              default:
                - attribute: filter_left
                  unit: hours
                  subtitle: Filter
                - attribute: side_brush_left
                  unit: hours
                  subtitle: Side brush
                - attribute: main_brush_left
                  unit: hours
                  subtitle: Main brush
                - attribute: sensor_dirty_left
                  unit: hours
                  subtitle: Sensors
              cleaning:
                - attribute: cleaned_area
                  unit: m2
                  subtitle: Cleaning area
                - attribute: cleaning_time
                  unit: minutes
                  subtitle: Cleaning time
            actions:
              - name: Clean living room
                service: script.clean_living_room
                icon: 'mdi:sofa'
              - name: Clean bedroom
                service: script.clean_bedroom
                icon: 'mdi:bed-empty'
              - name: Clean kitchen
                service: script.clean_kitchen
                icon: 'mdi:silverware-fork-knife'
          - type: 'custom:layout-break'
          - type: 'custom:button-card'
            color: auto
            color_type: blank-card
            styles:
              card:
                - height: 25px
          - type: 'custom:xiaomi-vacuum-map-card'
            entity: vacuum.xiaomi_vacuum_cleaner
            map_camera: camera.roborock
            camera_calibration: true
            calibration_points:
              - vacuum:
                  x: 25500
                  'y': 25500
                map:
                  x: 466
                  'y': 1889
              - vacuum:
                  x: 26500
                  'y': 26500
                map:
                  x: 730
                  'y': 1625
              - vacuum:
                  x: 25500
                  'y': 26500
                map:
                  x: 466
                  'y': 1625
            zones:
              - - - 25000
                  - 31000
                  - 30500
                  - 27500
              - - - 26000
                  - 23500
                  - 18750
                  - 27500
              - - - 26100
                  - 23500
                  - 30500
                  - 27400
              - - - 21000
                  - 19000
                  - 24250
                  - 23500
              - - - 17500
                  - 19000
                  - 21000
                  - 23500
              - - - 18750
                  - 23250
                  - 13000
                  - 28750
              - - - 24250
                  - 18750
                  - 31500
                  - 23500
          - type: 'custom:layout-break'
          - type: 'custom:button-card'
            color: auto
            color_type: blank-card
            styles:
              card:
                - height: 25px
          - type: 'custom:purifier-card'
            entity: fan.xiaomi_miio_device
            stats:
              - attribute: filter_life_remaining
                unit: '%'
                subtitle: Filter Remaining
              - attribute: motor_speed
                unit: RPS
                subtitle: Motor Speed
            actions:
              - name: Silent
                icon: 'mdi:weather-night'
                speed: Silent
              - name: 25%
                icon: 'mdi:circle-slice-2'
                speed: Favorite
                xiaomi_miio_favorite_level: 3
              - name: 50%
                icon: 'mdi:circle-slice-4'
                speed: Favorite
                xiaomi_miio_favorite_level: 7
              - name: 75%
                icon: 'mdi:circle-slice-6'
                speed: Favorite
                xiaomi_miio_favorite_level: 10
              - name: 100%
                icon: 'mdi:circle-slice-8'
                speed: Favorite
                xiaomi_miio_favorite_level: 14
              - name: Auto
                icon: 'mdi:brightness-auto'
                speed: Auto
            show_name: true
            show_state: true
            show_toolbar: true
            compact_view: false
  - !include views/view_camera.yaml
  - !include views/view_server.yaml
  - !include views/view_battery.yaml
