background: center / cover no-repeat fixed  url('/local/lovelace/bg_long.png?v=1')
kiosk_mode:
  mobile_settings:
    hide_header: true
views:
  - icon: "mdi:video-image"
    panel: false
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:layout-card
                layout_type: horizontal
                cards:
                  - !include
                    - ../templates/household_task.yaml
                    - name: Feed Dipshit
                      sensor_name: chore_feed_the_cat
                      warning_before: 1
                      cycle_days: 1

                  - !include
                    - ../templates/household_task.yaml
                    - name: Cut Claws
                      sensor_name: chore_cut_claws
                      warning_before: 1
                      cycle_days: 6

                  - !include
                    - ../templates/household_task.yaml
                    - name: Change Bed Sheets
                      sensor_name: chore_change_bed_sheets
                      warning_before: 1
                      cycle_days: 14

                  - !include
                    - ../templates/household_task.yaml
                    - name: Change HVAC Filters
                      sensor_name: chore_change_hvac_filters
                      warning_before: 1
                      cycle_days: 30

                  - !include
                    - ../templates/household_task.yaml
                    - name: Change Air Filters
                      sensor_name: chore_change_air_filters
                      warning_before: 1
                      cycle_days: 180

                  - !include
                    - ../templates/household_task.yaml
                    - name: Water Plants
                      sensor_name: chore_change_water_plants
                      warning_before: 1
                      cycle_days: 3

                  - !include
                    - ../templates/household_task.yaml
                    - name: Turn Mattress
                      sensor_name: chore_change_turn_mattress
                      warning_before: 1
                      cycle_days: 180

                  - !include
                    - ../templates/household_task.yaml
                    - name: Call Grandmother
                      sensor_name: chore_call_grandmother
                      warning_before: 1
                      cycle_days: 14
