- platform: bayesian
  name: Area - Bathroom Occupied
  prior: 0.2083
  device_class: occupancy
  probability_threshold: 0.70
  observations:
    - platform: "state"
      entity_id: binary_sensor.area_bathroom_humidity_trend
      prob_given_true: 0.0768
      prob_given_false: 0.0020
      to_state: "on"
    - platform: "state"
      entity_id: binary_sensor.motion_bathroom_home_security_motion_detection
      prob_given_true: 0.6720
      prob_given_false: 0.0531
      to_state: "on"
    - platform: "state"
      entity_id: sensor.motion_bathroom_illuminance
      prob_given_true: 1.2048
      prob_given_false: 0.2853
      to_state: "on"

- platform: bayesian
  name: Area - Bedroom Occupied
  prior: 0.5
  device_class: occupancy
  probability_threshold: 0.7
  observations:
    # - platform: "state"
    #   entity_id: "media_player.bedroom_tv"
    #   prob_given_true: 0.0300
    #   prob_given_false: 0.0015
    #   to_state: "playing"
    - platform: "state"
      entity_id: "input_boolean.bedtime"
      prob_given_true: 0.5940
      prob_given_false: 0.0891
      to_state: "on"
    # - platform: "state"
    #   entity_id: "binary_sensor.seb_sleeping"
    #   prob_given_true: 0.9680
    #   prob_given_false: 0.1452
    #   to_state: "on"
    # - platform: "state"
    #   entity_id: "media_player.bedroom_echo"
    #   prob_given_true: 0.0720
    #   prob_given_false: 0.0144
    #   to_state: "playing"
    - platform: "state"
      entity_id: "binary_sensor.sleep_schedule"
      prob_given_true: 0.8
      prob_given_false: 0.16
      to_state: "on"
    - platform: "state"
      entity_id: binary_sensor.multisensor_bedroom1_home_security_motion_detection
      prob_given_true: 0.1960
      prob_given_false: 0.0392
      to_state: "on"
    - platform: "state"
      entity_id: binary_sensor.area_bedroom_bright #"binary_sensor.area_bedroom1_bright"
      prob_given_true: 0.4040
      prob_given_false: 0.3838
      to_state: "on"
    - platform: "state"
      entity_id: "sun.sun"
      prob_given_true: 0.98
      prob_given_false: 0.6860
      to_state: "below_horizon"

- platform: bayesian
  prior: 0.5
  name: "Person1 - Sleeping"
  probability_threshold: 0.85
  observations:
    # - entity_id: 'group.tracked_users'
    #   prob_given_true: 0.99
    #   prob_given_false: 0.5
    #   platform: 'state'
    #   to_state: 'home'
    - entity_id: "sensor.sun"
      prob_given_true: 0.9
      prob_given_false: 0.2
      platform: "state"
      to_state: "below_horizon"
    # - entity_id: 'group.all_lights'
    #   prob_given_true: 0.9
    #   prob_given_false: 0.4
    #   platform: 'state'
    #   to_state: 'off'
    # - entity_id: 'sensor.coffeemaker'
    #   prob_given_true: 0.8
    #   prob_given_false: 0.4
    #   platform: 'state'
    #   to_state: 'Ready'
    # - entity_id: 'variable.last_motion'
    #   prob_given_true: 0.9
    #   prob_given_false: 0.3
    #   platform: 'state'
    #   to_state: 'Bathroom Motion'
    # - entity_id: 'binary_sensor.brad_phone_pluggedin'
    #   prob_given_true: 0.95
    #   prob_given_false: 0.5
    #   platform: 'state'
    #   to_state: 'on'
# sensor.stefanies_phone_detected_activity
#   = still, walking,

# binary_sensor.hd1905_keyguard_locked
#   = on = locked

# binary_sensor.hd1905_interactive
#   = phone in use

# sensor.stefanies_phone_battery_state
#   = discharging

# time > after 10pm.

