- platform: bayesian
  name: Area - Kitchen1 Occupied
  prior: 0.13
  device_class: occupancy
  probability_threshold: 0.80
  observations:
    - platform: "state"
      entity_id: binary_sensor.area_kitchen1_humidity_trend
      prob_given_true: 0.0768
      prob_given_false: 0.0020
      to_state: "on"
    - platform: "state"
      entity_id: binary_sensor.area_kitchen_motion
      prob_given_true: 0.96
      prob_given_false: 0.014
      to_state: "on"
    - platform: "state"
      entity_id: "schedule.kitchen_schedule"
      prob_given_true: 0.45
      prob_given_false: 0.048
      to_state: "on"

- platform: bayesian
  name: Area - Bathroom Occupied
  prior: 0.2083
  device_class: occupancy
  probability_threshold: 0.70
  observations:
    - platform: "state"
      entity_id: binary_sensor.area_bathroom_humidity_trend
      prob_given_true: 0.0768
      prob_given_false: 0.0020
      to_state: "on"
    - platform: "state"
      entity_id: binary_sensor.motion_bathroom_home_security_motion_detection
      prob_given_true: 0.6720
      prob_given_false: 0.0531
      to_state: "on"
    - platform: "state"
      entity_id: sensor.motion_bathroom_illuminance
      prob_given_true: 1.2048
      prob_given_false: 0.2853
      to_state: "on"

- platform: bayesian
  name: Area - Bedroom Occupied
  prior: 0.5
  device_class: occupancy
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "input_boolean.bedtime"
      prob_given_true: 0.5940
      prob_given_false: 0.0891
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.person1_sleeping"
      prob_given_true: 0.9680
      prob_given_false: 0.1452
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.sleep_schedule"
      prob_given_true: 0.8
      prob_given_false: 0.16
      to_state: "on"
    - platform: "state"
      entity_id: binary_sensor.multisensor_bedroom1_home_security_motion_detection
      prob_given_true: 0.1960
      prob_given_false: 0.0392
      to_state: "on"
    - platform: "state"
      entity_id: binary_sensor.area_bedroom_bright
      prob_given_true: 0.4040
      prob_given_false: 0.3838
      to_state: "on"
    - platform: "state"
      entity_id: "sun.sun"
      prob_given_true: 0.98
      prob_given_false: 0.6860
      to_state: "below_horizon"

- platform: bayesian
  name: Area - Livingroom Occupied
  prior: 0.29
  device_class: occupancy
  probability_threshold: 0.8
  observations:
    - platform: "state"
      entity_id: "binary_sensor.area_livingroom_motion"
      prob_given_true: 0.25
      prob_given_false: 0.0176
      to_state: "on"
    - platform: "state"
      entity_id: "media_player.livingroom_tv"
      prob_given_true: 0.3989
      prob_given_false: 0.0394
      to_state: "playing"
