- platform: ping
  host: www.github.com
  name: WAN Connected
  scan_interval: 60

- platform: ping
  host: !secret network_gateway
  name: Gateway
  scan_interval: 60

- platform: ping
  host: !secret network_wifi_ap1
  name: Network AP1
  scan_interval: 60

- platform: ping
  host: !secret network_wifi_ap2
  name: Network AP2
  scan_interval: 60
