- platform: trend
  sensors:
    area_bathroom_humidity_trend:
      friendly_name: Area - Bathroom Humidity Trend
      entity_id: sensor.motion_bathroom_humidity
      sample_duration: 1200
      max_samples: 6
      min_gradient: 0.011
      device_class: moisture
    area_bathroom_temperature_trend:
      friendly_name: Area - Bathroom Temperature Trend
      entity_id: sensor.multisensor_bathroom_air_temperature
      sample_duration: 1200
      max_samples: 6
      min_gradient: 0.0017
      device_class: heat
    # Bedroom1
    area_bedroom1_humidity_trend:
      friendly_name: Area - Bedroom1 Humidity Trend
      entity_id: sensor.multisensor_bedroom1_humidity
      sample_duration: 1200
      max_samples: 6
      min_gradient: 0.011
      device_class: moisture
