id: "d07e3bb9-5109-4d76-a883-bc025fc359f0"
alias: "System: Important Sensors are unavailable"
trigger:
  platform: state
  entity_id: binary_sensor.dws_unavailable
  to: "on"
action:
  - service: notify.admins
    data_template:
      message: "One or more of the alarm sensors is not reporting status changes. Check them!"
mode: single
