# #################################################################
# #                                                               #
# #                             UPS                               #
# #                                                               #
# #################################################################

# # switch:
# #   - platform: command_line
# #     switches:
# #       Mediacenter:
# #         oncmd: sudo etherwake so:me:th:in:ge:ad
# #         offcmd: ssh user@host sudo /sbin/shutdown -h now
# # https://cshire.xyz/scripting-synology-diskstation-remote-shutdowns/

alias: "UPS: UPS Discharging"
trigger:
  - platform: state
    entity_id: sensor.cyberpower_status_data
    to: "OB DISCHRG"
    from: "OL"
action:
  - service: notify.admins
    data:
      title: Home Assistant
      message: "System on battery."
