alias: "UPS Discharging - Critical"
trigger:
  - platform: state
    entity_id: sensor.myups_battery_runtime
condition:
  - condition: template
    value_template: "{{states('sensor.myups_battery_runtime')|int(0) < 300}}"
action:
  - service: notify.admins
    data:
      title: Home Assistant
      message: "System battery critical. Safely shutting everything down"
  # - service: switch.turn_on
  #   entity_id: switch.omv_nas
  - delay: "00:00:30"
  - service: shell_command.shutdown_omv
  - service: hassio.host_shutdown
