alias: "UPS: UPS Charging"
trigger:
  - platform: state
    entity_id: sensor.cyberpower_status_data
    to: "OL CHRG"
    for:
      minutes: 2
action:
  - service: notify.admins
    data:
      title: Home Assistant
      message: "System charging. Turning server back on."
# - service: switch.turn_on
#   entity_id: switch.omv_nas
