- id: '1613583163489'
  alias: Tag ea03378e-838b-493b-9920-28a728df67d8 is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: ea03378e-838b-493b-9920-28a728df67d8
  condition: []
  action:
  - service: lock.lock
    data: {}
    entity_id: lock.frontdoor_lock
  mode: single
- id: upstairs_scene_controller
  alias: SceneController Upstairs
  description: ''
  use_blueprint:
    path: philk/zen34-blueprint.yaml
    input:
      zwave_device: 9f43aee3bf7ab12f4221b7462c5431bd
      KeyPressed_Up:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.upstairs_livingroom
      KeyPressed_Down:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.upstairs_livingroom
      KeyPressed2x_Up:
      - service: light.turn_on
        target:
          entity_id: light.upstairs_kitchen
      KeyPressed2x_Down:
      - service: light.turn_off
        target:
          entity_id: light.upstairs_kitchen
      KeyPressed3x_Up: []
      KeyPressed3x_Down:
      - service: light.turn_on
        target:
          entity_id: light.bathroom2_lights
      - service: light.turn_off
        target:
          entity_id: light.bathroom2_lights
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
- id: '1626660542063'
  alias: Downstairs Scene Controller
  description: ''
  use_blueprint:
    path: philk/zen34-blueprint.yaml
    input:
      KeyPressed_Up:
      - service: light.turn_on
        target:
          device_id: 24f3de9ca06f58ad025f3c032fd9513f
      KeyPressed2x_Up:
      - service: light.turn_on
        target:
          entity_id:
          - light.frontroom_ceiling
          - light.unit1_livingroom_lamp
      KeyPressed_Down:
      - service: light.turn_off
        target:
          device_id: 24f3de9ca06f58ad025f3c032fd9513f
      KeyPressed2x_Down:
      - service: light.turn_off
        target:
          device_id:
          - 24f3de9ca06f58ad025f3c032fd9513f
          entity_id: light.unit1_livingroom_lamp
      zwave_device: d25a719d48bd81d2fadf702fec723708
      KeyPressed3x_Down:
      - service: script.person1_bedtime
- id: '1633398975580'
  alias: Dim Lights when Roku Plays
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.50_tcl_roku_tv
    to: playing
  condition:
  - condition: time
    after: '19:00:00'
  action:
  - service: light.turn_on
    data:
      brightness: 52
      kelvin: 2700
    target:
      device_id: 24f3de9ca06f58ad025f3c032fd9513f
  - service: switch.turn_on
    target:
      entity_id:
      - switch.light_end_table
  mode: single
- id: '1633398975581'
  alias: Dim Lights when Roku Stops
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.50_tcl_roku_tv
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 254
      kelvin: 2700
    target:
      device_id: 24f3de9ca06f58ad025f3c032fd9513f
  mode: single
- id: '1636204191724'
  alias: Bedroom2 Scene Controller
  description: ''
  use_blueprint:
    path: philk/zen34-blueprint.yaml
    input:
      zwave_device: 909ee6b4eed3ef8f4b7d4e5874683c59
      KeyPressed_Up:
      - service: light.turn_on
        target:
          entity_id: light.unit2_loft_fairy_lights
      KeyPressed_Down:
      - service: light.turn_off
        target:
          entity_id: light.unit2_loft_fairy_lights
      KeyPressed2x_Down:
      - service: light.turn_off
        target:
          entity_id: light.upstairs
        data: {}
- id: '1636741737566'
  alias: 'Lights: Office Control (Off)'
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: f3084def3592eab42ec87953c00b8994
    entity_id: switch.upstairs_office
    domain: switch
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.upstairs_office
    data:
      transition: 0
  mode: single
- id: '1637797146793'
  alias: 'Scene: Person1 Nightstand'
  description: ''
  use_blueprint:
    path: Net_Giant/hank-electronics-hkzw-scn04-4-button-scene-controller-for-z-wave-js.yaml
    input:
      scn04: 334bc900119105387c182c00f3ee5d74
      button_1_press:
      - service: script.person1_bedtime
        data: {}
      button_4_press:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.person1_nightlight
      button_3_press:
      - service: light.toggle
        data:
          transition: 0
        target:
          entity_id: light.bedroom1_ceiling
- id: '1637809006304'
  alias: 'Scene: Person 2 Nightstand'
  description: ''
  use_blueprint:
    path: Net_Giant/hank-electronics-hkzw-scn04-4-button-scene-controller-for-z-wave-js.yaml
    input:
      scn04: 3fa221e521cdb92e0ad30b47591ab2a5
      button_1_press:
      - service: light.turn_off
        target:
          device_id: e7673bb818654bb0023b5e4a4e8afbda
          area_id: bathroom1
        data: {}
      button_4_press:
      - service: light.toggle
        target:
          entity_id:
          - light.person2_nightlight
          - light.person1_nightlight
        data: {}
      button_3_press:
      - service: light.toggle
        data: {}
        target:
          entity_id: bedroom
- id: '1640010598036'
  alias: 'Scene: Office2 Light Control'
  description: ''
  trigger:
  - platform: device
    device_id: f3084def3592eab42ec87953c00b8994
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: '002'
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 002
    value: 3
  - platform: device
    device_id: f3084def3592eab42ec87953c00b8994
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: '001'
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
  condition: []
  action:
  - service: light.toggle
    data:
      transition: 0
    target:
      entity_id:
      - light.upstairs_office
  mode: single
- id: '1648903329498'
  alias: 'Scene: Person 2 Nightstand'
  description: ''
  use_blueprint:
    path: Net_Giant/hank-electronics-hkzw-scn04-4-button-scene-controller-for-z-wave-js.yaml
    input:
      scn04: 3fa221e521cdb92e0ad30b47591ab2a5
      button_1_press:
      - service: script.person1_bedtime
        data: {}
      button_3_press:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.person2_nightlight
      button_4_press:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.bedroom1_ceiling
- id: '1649607077145'
  alias: 'Garden: Livingroom Plant Lights (On)'
  description: ''
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.unit1_socket_livingroom_couch_2
  mode: single
- id: '1649607132311'
  alias: 'Garden: Living room plant (Off)'
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.unit1_socket_livingroom_couch_2
  mode: single
- id: '1650325543337'
  alias: 'Lights: Bedroom2 Auto-On'
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  condition:
  - condition: state
    entity_id: person.jenn
    state: home
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.unit2_loft_fairy_lights_2
  mode: single
- id: '1652546048785'
  alias: 'Light: Motion Kitchen1'
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: aedd405fc241d17af5e5ba329b23f3c0
    entity_id: binary_sensor.multisensor_home_security_motion_detection_3
    domain: binary_sensor
  condition:
  - condition: time
    before: '22:00:00'
    after: 06:00:00
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.kitchen1_lights
  mode: single
- id: '1653677869258'
  alias: Ding Dong on Door Open
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 5dee3d4f9f2baca45dde13721d9a0dc0
    entity_id: binary_sensor.motion_bedroom1_home_security_motion_detection
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: b35def9d0bb5b95c4d037c1247a949d7
    entity_id: switch.wink_siren
    domain: switch
  mode: single
