- id: '1611013578242'
  alias: Tag b8901fe6-ad65-45c8-9f3d-e24bf8b62c63 is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: b8901fe6-ad65-45c8-9f3d-e24bf8b62c63
  condition: []
  action:
  - service: automation.trigger
    data: {}
    entity_id: automation.cat_has_been_fed
  mode: single
- id: '1613583163489'
  alias: Tag ea03378e-838b-493b-9920-28a728df67d8 is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: ea03378e-838b-493b-9920-28a728df67d8
  condition: []
  action:
  - service: lock.lock
    data: {}
    entity_id: lock.frontdoor_lock
  mode: single
- id: '1618690465011'
  alias: Motion Light Bathroom 2
  description: ''
  use_blueprint:
    path: freakshock88/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.motion_bathroom2_home_security_motion_detection
      target_entity: switch.light_bathroom2
      no_motion_wait: input_number.bathroom2_off_duration
- id: upstairs_scene_controller
  alias: SceneController Upstairs
  description: ''
  use_blueprint:
    path: philk/zen34-blueprint.yaml
    input:
      zwave_device: 9f43aee3bf7ab12f4221b7462c5431bd
      KeyPressed_Up:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.upstairs_livingroom
      KeyPressed_Down:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.upstairs_livingroom
      KeyPressed2x_Up:
      - service: light.turn_on
        target:
          entity_id: light.upstairs_kitchen
      KeyPressed2x_Down:
      - service: light.turn_off
        target:
          entity_id: light.upstairs_kitchen
      KeyPressed3x_Up: []
      KeyPressed3x_Down:
      - service: light.turn_on
        target:
          entity_id: light.bathroom2_lights
      - service: light.turn_off
        target:
          entity_id: light.bathroom2_lights
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
          milliseconds: 0
- id: '1626660542063'
  alias: Downstairs Scene Controller
  description: ''
  use_blueprint:
    path: philk/zen34-blueprint.yaml
    input:
      KeyPressed_Up:
      - service: light.turn_on
        target:
          device_id: 24f3de9ca06f58ad025f3c032fd9513f
      KeyPressed2x_Up:
      - service: light.turn_on
        target:
          entity_id:
          - light.frontroom_ceiling
          - light.unit1_livingroom_lamp
      KeyPressed_Down:
      - service: light.turn_off
        target:
          device_id: 24f3de9ca06f58ad025f3c032fd9513f
      KeyPressed2x_Down:
      - service: light.turn_off
        target:
          device_id:
          - 24f3de9ca06f58ad025f3c032fd9513f
          entity_id: light.unit1_livingroom_lamp
      zwave_device: d25a719d48bd81d2fadf702fec723708
      KeyPressed3x_Down:
      - service: script.person1_bedtime
- id: '1633398975580'
  alias: Dim Lights when Roku Plays
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.50_tcl_roku_tv
    to: playing
  condition:
  - condition: time
    after: '19:00:00'
  action:
  - service: light.turn_on
    data:
      brightness: 52
      kelvin: 2700
    target:
      device_id: 24f3de9ca06f58ad025f3c032fd9513f
  - service: switch.turn_on
    target:
      entity_id:
      - switch.light_end_table
  mode: single
- id: '1633398975581'
  alias: Dim Lights when Roku Stops
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.50_tcl_roku_tv
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 254
      kelvin: 2700
    target:
      device_id: 24f3de9ca06f58ad025f3c032fd9513f
  mode: single
- id: '1636204191724'
  alias: Bedroom2 Scene Controller
  description: ''
  use_blueprint:
    path: philk/zen34-blueprint.yaml
    input:
      zwave_device: 909ee6b4eed3ef8f4b7d4e5874683c59
      KeyPressed_Up:
      - service: light.turn_on
        target:
          entity_id: light.unit2_loft_fairy_lights
      KeyPressed_Down:
      - service: light.turn_off
        target:
          entity_id: light.unit2_loft_fairy_lights
      KeyPressed2x_Down:
      - service: light.turn_off
        target:
          entity_id: light.upstairs
        data: {}
