- platform: workday
  name: Workday Today
  country: !secrets country
  province: !secrets province

- platform: workday
  name: Workday Tomorrow
  country: !secrets country
  province: !secrets province
  days_offset: 1

- platform: tod
  name: evening
  after: sunset
  after_offset: '-00:30'
  before: '23:59'

- platform: tod
  name: night
  after: '23:59'
  before: '05:30' 