# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

history:
  include:
    domains:
      - light
    entity_globs:
      - binary_sensor.*_motion

homeassistant:
  packages: !include_dir_named configuration/
  customize: !include customize.yaml

  auth_providers:
    - type: homeassistant
    - type: command_line
      command: /config/shell/ldap-auth.sh
      args: ["/config/shell/ldap-auth.cfg"]
      meta: true

http:
  ssl_certificate: ssl/home-assistant.local.pem
  ssl_key: ssl/home-assistant.local-key.pem

frontend:
  themes: !include_dir_merge_named themes

scene: !include scenes.yaml
automation ui: !include automations.yaml
automation manual: !include_dir_merge_named automation/

browser_mod:
powercalc:

logger:
  default: info
  logs:
    # Reduces excessive logging for these automations.
    homeassistant.components.automation.occupancy_person_1_room_location: error
    homeassistant.components.automation.light_autooff_kitchen: error
    homeassistant.components.automation.light_autooff_backroom: error
    homeassistant.components.automation.light_autooff_frontroom: error
    homeassistant.components.automation.lights_autooff_frontroom: error

# Text to speech
tts:
  - platform: google_translate

# Use MariaDb
recorder:
  db_url: !secret db_url
  purge_keep_days: 3
  auto_purge: true
  exclude:
    entities:
      - sun.sun
      - sensor.date
    entity_globs:
      - media_player.*
      - sensor.emby*
      - automation.occupancy_*
      - sensor.*rx*
      - sensor.*tx*
      - binary_sensor.edgeos_interface_*
      - sensor.daily_internet_usage*
      - input_select.*_location
      - sensor.hass_docker_*
      - sensor.uptime*
      - device_tracker*
      - sensor.internet_mb_uploaded
      - sensor.internet_mb_downloaded

influxdb:
  host: !secret influxdb_url
  port: 8086
  database: home_assistant
  exclude:
    domains:
      - persistent_notification
      - person
    entity_globs:
      - media_player.*
      - sensor.emby*
      - automation.occupancy_*
      - sensor.*rx*
      - sensor.*tx*
      - binary_sensor.edgeos_interface_*
      - sensor.daily_internet_usage*
      - input_select.*_location

media_player:
  # - platform: snapcast
  #   host: !secret snapcast_server

  - platform: mpd
    host: !secret mopidy_multiroom
    port: 6600
    name: Multi-Room Controller

counter:
  front_door:
    initial: 0
    step: 1
