# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

history:
  include:
    domains:
      - light
    entity_globs:
      - binary_sensor.*_motion

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml 

frontend:
  themes: !include_dir_merge_named themes

<<<<<<< Updated upstream
=======
lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Home
      icon: mdi:script
      show_in_sidebar: true
      filename: lovelace/tablet.yaml
    lovelace-system:
      mode: yaml
      filename: lovelace/ui-system.yaml
      title: "System"
      icon: mdi:view-dashboard
      show_in_sidebar: true
      require_admin: false

>>>>>>> Stashed changes
panel_iframe:
  nodered:
    title: 'NodeRed'
    url: !secret app_nodered_url
    icon: mdi:chip
    require_admin: true
  esphome:
    title: 'EspHome'
    icon: mdi:chip
    url: !secret app_esphome_url
  z2m:
    title: 'ZWave'
    url: !secret app_zwave_url
    icon: mdi:home
  portainer:
    title: 'Portainer'
    icon: mdi:docker
    url: !secret app_portainer_url

input_boolean: !include input_boolean.yaml
binary_sensor: !include binary_sensors.yaml

group: !include_dir_merge_named group/
script: !include_dir_named scripts/
automation ui: !include automations.yaml
automation manual: !include_dir_list automation/

browser_mod:

logger:
  default: info

# Text to speech
tts:
  - platform: google_translate

# Use MariaDb
recorder:
  db_url: !secret db_url
  purge_keep_days: 3
  auto_purge: true

influxdb:
  host: influxdb
  port: 8086
  database: home_assistant

notify:
  - name: STANDARD_EMAIL
    username: !secret email_username
    password: !secret email_password
    platform: smtp
    sender: !secret sender_email
    recipient: !secret my_email
    server: !secret email_host
    port: 465
    encryption: tls
  
  - name: ALL
    platform: group
    services:
      - service: !secret person1_mobile
      - service: !secret person2_mobile
      - service: !secret person3_mobile

  - name: android
    platform: group
    services:
      - service: !secret person1_mobile
      - service: !secret person2_mobile

  - name: iphone
    platform: group
    services:
      - service: !secret person3_mobile

  - name: home_automation
    platform: group
    services:
      - service: !secret person2_mobile
        data:
          title: 'Enable Home automation?'
          data:
            push:
              badge: 0
              category: "home_automation"

  - name: admins
    platform: group
    services:
      - service: !secret person2_mobile