# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

history:
  include:
    domains:
      - light
    entity_globs:
      - binary_sensor.*_motion

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml

http:
  ssl_certificate: ssl/fullchain.pem
  ssl_key: ssl/privkey.pem

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  dashboards:
    #
    # Mobile Dashboard + Sub-Dashboards
    #
    lovelace-demo:
      mode: yaml
      title: Mobile
      icon: mdi:view-dashboard
      show_in_sidebar: true
      require_admin: false
      filename: lovelace/dashboard.yaml
    sub-security:
      mode: yaml
      title: Security
      show_in_sidebar: false
      require_admin: false
      filename: lovelace/sub-views/security.yaml
    sub-cameras:
      mode: yaml
      title: Cameras
      show_in_sidebar: false
      require_admin: false
      filename: lovelace/sub-views/cameras.yaml
    sub-admin:
      mode: yaml
      title: Admin
      show_in_sidebar: false
      require_admin: false
      filename: lovelace/sub-views/admin.yaml
    sub-fan:
      mode: yaml
      title: Fans
      show_in_sidebar: false
      require_admin: false
      filename: lovelace/sub-views/fan.yaml
    sub-hvac:
      mode: yaml
      title: HVAC
      show_in_sidebar: false
      require_admin: false
      filename: lovelace/sub-views/hvac.yaml
    sub-music:
      mode: yaml
      title: Music
      show_in_sidebar: false
      require_admin: false
      filename: lovelace/sub-views/music.yaml
    sub-remotes:
      mode: yaml
      title: Remotes
      show_in_sidebar: false
      require_admin: false
      filename: lovelace/sub-views/remotes.yaml

input_boolean: !include input_boolean.yaml
binary_sensor: !include binary_sensors.yaml

group: !include_dir_merge_named group/
script: !include_dir_named scripts/
automation ui: !include automations.yaml
automation manual: !include_dir_list automation/

browser_mod:

logger:
  default: info

localtuya:
  - host: 192.168.30
    device_id: 08102037e8db84b81c50
    local_key: dba2c9a835a3456999e66c25ae2fba09
    friendly_name: Tuya Device
    protocol_version: "3.3"
    entities:
      - platform: binary_sensor
        friendly_name: Plug Status
        id: 1
        device_class: power
        state_on: "true" # Optional
        state_off: "false" # Optional

# Text to speech
tts:
  - platform: google_translate

# Use MariaDb
recorder:
  db_url: !secret db_url
  purge_keep_days: 3
  auto_purge: true
  exclude:
    entities:
      - sun.sun
      - sensor.date
    entity_globs:
      - media_player.*
      - sensor.emby*

influxdb:
  host: influxdb
  port: 8086
  database: home_assistant

notify:
  - name: STANDARD_EMAIL
    username: !secret email_username
    password: !secret email_password
    platform: smtp
    sender: !secret sender_email
    recipient: !secret my_email
    server: !secret email_host
    port: 465
    encryption: tls

  - name: ALL
    platform: group
    services:
      - service: !secret person1_mobile
      - service: !secret person2_mobile
      - service: !secret person3_mobile

  - name: android
    platform: group
    services:
      - service: !secret person1_mobile

  - name: iphone
    platform: group
    services:
      - service: !secret person2_mobile
      - service: !secret person3_mobile

  - name: home_automation
    platform: group
    services:
      - service: !secret person2_mobile
        data:
          title: "Enable Home automation?"
          data:
            push:
              badge: 0
              category: "home_automation"

  - name: admins
    platform: group
    services:
      - service: !secret person2_mobile

media_player:
  - platform: snapcast
    host: !secret snapcast_server

  - platform: mpd
    host: !secret mopidy_multiroom
    port: 6600
    name: Multi-Room Controller
