# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

history:
  include:
    domains:
      - light
    entity_globs:
      - binary_sensor.*_motion

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml 

frontend:
  themes: !include_dir_merge_named themes

browser_mod:

logger:
  default: info

# Text to speech
tts:
  - platform: google_translate

# Use MariaDb
recorder:
  db_url: !secret db_url
  purge_keep_days: 3
  auto_purge: true

influxdb:
  host: influxdb
  port: 8086
  database: home_assistant

notify:
  - name: STANDARD_EMAIL
    username: !secret email_username
    password: !secret email_password
    platform: smtp
    sender: !secret sender_email
    recipient: !secret my_email
    server: !secret email_host
    port: 465
    encryption: tls
  
  - name: ALL
    platform: group
    services:
      - service: !secret person1_mobile
      - service: !secret person2_mobile
      - service: !secret person3_mobile

  - name: android
    platform: group
    services:
      - service: !secret person1_mobile
      - service: !secret person2_mobile

  - name: iphone
    platform: group
    services:
      - service: !secret person3_mobile

  - name: home_automation
    platform: group
    services:
      - service: !secret person2_mobile
        data:
          title: 'Enable Home automation?'
          data:
            push:
              badge: 0
              category: "home_automation"

  - name: admins
    platform: group
    services:
      - service: !secret person2_mobile