binary_sensor:
  - platform: bayesian
    name: Area - Bedroom Occupied
    prior: 0.5
    device_class: occupancy
    probability_threshold: 0.7
    observations:
      # - platform: "state"
      #   entity_id: "media_player.bedroom_tv"
      #   prob_given_true: 0.0300
      #   prob_given_false: 0.0015
      #   to_state: "playing"
      - platform: "state"
        entity_id: "input_boolean.bedtime"
        prob_given_true: 0.5940
        prob_given_false: 0.0891
        to_state: "on"
      # - platform: "state"
      #   entity_id: "binary_sensor.seb_sleeping"
      #   prob_given_true: 0.9680
      #   prob_given_false: 0.1452
      #   to_state: "on"
      # - platform: "state"
      #   entity_id: "media_player.bedroom_echo"
      #   prob_given_true: 0.0720
      #   prob_given_false: 0.0144
      #   to_state: "playing"
      - platform: "state"
        entity_id: "binary_sensor.sleep_schedule"
        prob_given_true: 0.8
        prob_given_false: 0.16
        to_state: "on"
      - platform: "state"
        entity_id: "binary_sensor.motion_bedroom1_home_security_motion_detection"
        prob_given_true: 0.1960
        prob_given_false: 0.0392
        to_state: "on"
      - platform: "state"
        entity_id: binary_sensor.area_bedroom_bright #"binary_sensor.area_bedroom1_bright"
        prob_given_true: 0.4040
        prob_given_false: 0.3838
        to_state: "on"
      - platform: "state"
        entity_id: "sun.sun"
        prob_given_true: 0.98
        prob_given_false: 0.6860
        to_state: "below_horizon"

template:
  - binary_sensor:
      - unique_id: area_bedroom1_bright
        name: "Area - Bedroom1 Bright"
        device_class: light
        attributes:
          current_illuminance: "{{ (states('sensor.motion_bedroom1_illuminance') | float) }}"
          light_state: "{{ states('light.bedroom_lights') }}"
          sun: "{{ states('sun.sun') }}"
        state: "{{ (states('sensor.motion_bedroom1_illuminance') | int > states('input_number.area_bedroom_lux_level') | int) and (is_state('sun.sun', 'above_horizon') or is_state('light.bedroom1', 'off')) }}"

      - unique_id: "area_bedroom1_occupied"
        name: Bedroom1 Occupied
        device_class: "occupancy"
        delay_off:
          minutes: 5
        state: >-
          {{ is_state('binary_sensor.motion_bedroom1_home_security_motion_detection', 'on' )
              or (is_state('input_boolean.bedtime', 'on'))
          }}

      - unique_id: "sleep_schedule"
        name: Sleep Schedule
        icon: mdi:clock
        state: >
          {% set current_time = now().strftime("%H:%M")  %}
          {% set time_limit_before= states('input_datetime.time_typically_sleeping_start') %}
          {% set time_limit_after = states('input_datetime.time_typically_sleeping_start') %}

          {% if time_limit_before == none and time_limit_after == none %}
          true
          {% endif %}

          {% if time_limit_before != none and time_limit_after == none %}
          {% set current_time_is_before_limit = current_time < time_limit_before  %}
          {{ current_time_is_before_limit }}
          {% elif time_limit_before == none and time_limit_after != none %}
          {% set current_time_is_after_limit = current_time > time_limit_after  %}
          {{ current_time_is_after_limit }}
          {% endif %}

          {% if time_limit_before != none and time_limit_after != none %}
          {% set before_limit_is_tomorrow = time_limit_before < time_limit_after  %}
          {% set current_time_is_before_limit = current_time < time_limit_before  %}
          {% set current_time_is_after_limit = current_time > time_limit_after  %}
          {% set time_window_spans_midnight = time_limit_after > time_limit_before  %}
            {% if time_window_spans_midnight != none and time_window_spans_midnight and before_limit_is_tomorrow %}
            {{ current_time_is_after_limit or current_time_is_before_limit }}
            {% elif time_window_spans_midnight != none and not time_window_spans_midnight %}
            {{ current_time_is_before_limit and current_time_is_after_limit }}
            {% endif %}
          {% endif %}

sensor:
  ## Area Entities
  - platform: history_stats
    name: Stats - Bedroom1 Bright
    entity_id: binary_sensor.area_bedroom1_bright
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      days: 7
  - platform: history_stats
    name: Stats - Bedroom1 Humidity Trend
    entity_id: binary_sensor.motion_bedroom1_humidity
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      days: 7
  - platform: history_stats
    name: Stats - Bedroom1 Occupied
    entity_id: binary_sensor.area_bedroom1_occupied
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      days: 7
  - platform: history_stats
    name: Stats - Bedroom1 Temperature Trend
    entity_id: sensor.motion_bedroom1_air_temperature
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      days: 7
  - platform: history_stats
    name: Stats - Bedroom1 Motion
    entity_id: binary_sensor.motion_bedroom1_home_security_motion_detection
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      days: 7
