id: "9ffe3b15-f9fd-41d4-88df-9fc07cdc2199"
alias: "Locks: Unlock frontdoor if tag scanned"
description: ""
trigger:
  - platform: tag
    tag_id: ea03378e-838b-493b-9920-28a728df67d8
condition: []
action:
  - service: lock.unlock
    entity_id: lock.frontdoor_lock
mode: single
