- platform: powercalc
  entity_id: light.frontroom_ceiling
  fixed:
    power: 36

- platform: powercalc
  entity_id: light.ceiling
  fixed:
    power: 36

- platform: powercalc
  entity_id: light.diningroom_ceiling
  fixed:
    power: 18
