- platform: powercalc
  entity_id: light.frontroom_ceiling
  fixed:
    power: 36

- platform: powercalc
  entity_id: light.ceiling
  fixed:
    power: 36

- platform: mqtt
  name: "Shelly1PM-example"
  unique_id: "shelly_1pm_example"
  state_topic: "shellies/shelly1pm-765D8E/relay/0/power"
