- platform: filter
  name: "Basement Realistic Humidity"
  entity_id: sensor.basement_humidity
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

- platform: filter
  name: "Bedroom1 Realistic Humidity"
  entity_id: sensor.multisensor_bedroom1_humidity
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

- platform: filter
  name: "Bedroom2 Realistic Humidity"
  entity_id: sensor.upper_office_multisensor_humidity # todo - rename sensor.
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2

- platform: min_max
  name: Area - Household Humidity
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.bedroom1_realistic_humidity
    - sensor.multisensor_kitchen1_humidity
    - sensor.multisensor_bathroom1_humidity
    - sensor.multisensor_frontroom_humidity
