- platform: mqtt
  name: MQTT Messages
  state_topic: "$SYS/broker/messages/received"

- platform: mqtt
  name: MQTT Clients
  state_topic: "$SYS/broker/clients/total"

- platform: mqtt
  name: MQTT Subscriber Count
  state_topic: "$SYS/broker/subscriptions/count"

- platform: mqtt
  name: MQTT Retained Message Count
  state_topic: "$SYS/broker/retained messages/count"
