#
# System Monitor
#
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: "/"
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: network_in
      arg: en0
    - type: network_out
      arg: en0
