- platform: filter
  name: "Bedroom1 Realistic Temperature"
  entity_id: sensor.motion_bedroom1_air_temperature
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0
    - filter: lowpass
      time_constant: 10
      precision: 2
