#################################################################
#                                                               #
#                              Cats                             #
#                                                               #
#################################################################

input_datetime:
  cat_last_fed:
    name: "cat_last_fed"
    has_date: true
    has_time: true

sensor:
  - platform: template
    sensors:
      cat_last_fed:
        friendly_name: "Cat last fed"
        unit_of_measurement: "hours(s) ago"
        value_template: >
          {{ ((now().timestamp() - state_attr('input_datetime.cat_last_fed','timestamp'))/(60*60)) | round(0, 'floor') |int(0) }}

binary_sensor:
  - platform: template
    sensors:
      cat_needs_feeding:
        friendly_name: "Cat needs feeding"
        value_template: >
          {{ states('sensor.cat_last_fed')|int(0) >= 9 and ((now().hour <= 9 and now().hour >= 7) or (now().hour >= 18 and now().hour <= 20)) }}

automation:
  - id: "9da4630f-a4fe-46ca-a9bc-1adf1f0b669b"
    alias: Has the cat been fed yet?
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.cat_needs_feeding
        to: "on"
    condition: []
    action:
      - repeat:
          count: 3
          sequence:
            - condition: template
              value_template: "{{ is_state('binary_sensor.cat_needs_feeding', 'on')}}"
            - service: notify.all
              data:
                title: "Animal Welfare"
                message: "Have you fed Dipshit?"
                data:
                  tag: "cat-feeding"
                  actions:
                    - action: has_been_fed
                      title: "Yes"
                  push:
                    badge: 5
            - wait_for_trigger:
                - platform: template
                  value_template: "{{ not is_state('binary_sensor.cat_needs_feeding', 'on')}}"
              timeout: 1800 # 30 Minutes
    mode: single
  - id: "e677e588-369a-4113-b9d1-50a48feccc6d"
    alias: Cat has been fed
    description: Clears alerts when the cat has been fed
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: has_been_fed
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          actionName: HAS_BEEN_FED
      - platform: tag
        tag_id: b8901fe6-ad65-45c8-9f3d-e24bf8b62c63
    condition: []
    action:
      - service: input_datetime.set_datetime
        data:
          datetime: "{{ now().isoformat() }}"
        entity_id: input_datetime.cat_last_fed
      - service: notify.all
        data:
          title: "Dhipshit"
          message: "Dipshit has been fed"
          data:
            tag: "cat-feeding"
    mode: single
