homeassistant:
  customize:
    package.occupancy:
      location_states: &location_states
        options:
          - Unknown
          - Just Arrived
          - Home
          - Just Left
          - Away
          - Extended Away

          - Downstairs
          - Kitchen
          - Frontroom
          - Backroom
          - Bedroom1

          - Upstairs
          - Livingroom
          - Bedroom2
          - Bathroom
          - Office

input_select:
  stefanie_location:
    <<: *location_states

  richard_location:
    <<: *location_states

  jenn_location:
    <<: *location_states
