#################################################################
#                                                               #
#                          Automations                          #
#                                                               #
#################################################################
automation:
  - id: "330757ab-210e-4a78-8743-693cca42c9eb"
    alias: "Ssystem: Update VERIFY"
    trigger:
      # When Home Assistant starts.
      - platform: homeassistant
        event: start
      # Every 6 hours.
      - platform: time_pattern
        hours: "/6"
        minutes: 00
    action:
      # Wait a while so that everything is ready.
      - delay: 30
      # Force a refresh of the updater component.
      - service: homeassistant.update_entity
        entity_id: binary_sensor.updater

  ## Notify if we're running out of disk space on the main home-assistant server.
  - alias: "System: Disk Use Alarm"
    initial_state: "on"
    trigger:
      platform: numeric_state
      entity_id: sensor.disk_use_percent
      above: 12
    action:
      - service: notify.admins
        data:
          title: "HA HASSIO Server"
          message: "Warning - HA Server Disk Use is {{states.sensor.disk_use.state}}Gb"

utility_meter:
  wan_in_monthly:
    source: sensor.internet_gb_downloaded
    cycle: monthly

  wan_in_daily:
    source: sensor.internet_gb_downloaded
    cycle: daily

  wan_out_monthly:
    source: sensor.internet_gb_uploaded
    cycle: monthly

  wan_out_daily:
    source: sensor.internet_gb_uploaded
    cycle: daily
