graph_environment:
  card:
    type: custom:apexcharts-card
    graph_span: 6h
    header:
      show: true
      floating: true
      show_states: true
    experimental:
      color_threshold: true
    series:
      - entity: "[[temperature_entity]]"
        type: line
        name: Temperature
        color_threshold:
          - color: "#a55eea"
            value: 19.58
          - color: "#8854d0"
            value: 24.98
          - color: "#3867d6"
            value: 29.84
          - color: "#4b7bec"
            value: 34.88
          - color: "#2d98da"
            value: 39.74
          - color: "#45aaf2"
            value: 44.78
          - color: "#0fb9b1"
            value: 49.82
          - color: "#2bcbba"
            value: 54.86
          - color: "#20bf6b"
            value: 59.9
          - color: "#26de81"
            value: 64.76
          - color: "#fed330"
            value: 69.8
          - color: "#f7b731"
            value: 74.84
          - color: "#fd9644"
            value: 79.88
          - color: "#fa8231"
            value: 84.74
          - color: "#eb3b5a"
            value: 96.62
        group_by:
          func: avg
          duration: 30min
      - entity: "[[humidity_entity]]"
        type: column
        name: Humidity
        group_by:
          func: avg
          duration: 30min
