popup_environment:
  default:
    - icon: mdi:run

  #
  # sensor.multisensor_air_temperature - bathroom1
  # sensor.multisensor_air_temperature_2 - living room
  # sensor.multisensor_air_temperature_2 - kitchen
  # sensor.multisensor_air_temperature_4 - bedroom1
  # sensor.unit_1_mudroom_temperature - mudroom
  # sensor.unit_2_kitchen_temperature
  # sensor.upper_office_multisensor_temperature

  card:
    type: "custom:bootstrap-grid-card"
    cards:
      - type: row
        cards:
          - type: col
            class: "col-12 col-sm-12 col-md-6 col-lg-6"
            cards:
              - type: custom:apexcharts-card
                graph_span: 1d
                # span:
                #   start: minute
                update_interval: 1h
                header:
                  title: ""
                  show: true
                  show_states: true
                  colorize_states: false
                style: |
                  ha-card {
                    --ha-card-background: rgba(0, 0, 0, 0);
                    box-shadow: none;
                    margin: 8px 8px 38px 8px;
                    font-size: 15px;
                    font-family: 'Segoe UI Light";
                    text-align: center
                  }
                  div#header__title {
                    font-size: 20px;
                    font-weight: 300;
                    font-family: 'Segoe UI Light";
                    font-color: #ff0000
                  }
                all_series_config:
                  stroke_width: 2
                apex_config:
                  annotations:
                    position: back
                    yaxis:
                      - "y": 0
                        strokeDashArray: 5
                        borderColor: "#5b5b5b"
                        borderWidth: 1
                    #     xaxis:
                    #       labels:
                    #         format: HH
                    #       axisBorder:
                    #         show: false
                    #     legend:
                    #       show: false
                  grid:
                    show: false
                  # fill:
                  #   type: gradient
                  #   gradient:
                  #     type: vertical
                  #     shadeIntensity: 0.4
                  #     opacityFrom: 0.9
                  #     opacityTo: 0
                  #     stops:
                  #       - 1
                  #       - 95
                  #       - 100
                  chart:
                    dropshadow:
                      enabled: true
                    height: 300px
                    width: 100%
                # experimental:
                #   color_threshold: true
                series:
                  - entity: sensor.upper_office_multisensor_temperature
                    type: line
                    name: Office2

                  - entity: sensor.multisensor_air_temperature
                    type: line
                    name: Bathroom1

                  - entity: sensor.multisensor_air_temperature_3
                    type: line
                    name: Kitchen1

                  - entity: sensor.multisensor_air_temperature_4
                    type: line
                    name: Bedroom1

                  - entity: sensor.multisensor_air_temperature_2
                    type: line
                    name: Frontroom

                  - entity: weather.home
                    type: area
                    attribute: temperature
                    fill_raw: last
                    extend_to_end: false
                    name: "Outside Temp."
                    group_by:
                      func: avg
                      duration: 2h
                  #     #
                  #   # sensor.multisensor_air_temperature - bathroom1
                  #   # sensor.multisensor_air_temperature_2 - living room
                  #   # sensor.multisensor_air_temperature_2 - kitchen
                  #   # sensor.multisensor_air_temperature_4 - bedroom1
                  #   # sensor.unit_1_mudroom_temperature - mudroom
                  #   # sensor.unit_2_kitchen_temperature
                  #   # sensor.upper_office_multisensor_temperature
                  #   # color_threshold:
                  #   #   - color: "#a55eea"
                  #   #     value: 19.58
                  #   #   - color: "#8854d0"
                  #   #     value: 24.98
                  #   #   - color: "#3867d6"
                  #   #     value: 29.84
                  #   #   - color: "#4b7bec"
                  #   #     value: 34.88
                  #   #   - color: "#2d98da"
                  #   #     value: 39.74
                  #   #   - color: "#45aaf2"
                  #   #     value: 44.78
                  #   #   - color: "#0fb9b1"
                  #   #     value: 49.82
                  #   #   - color: "#2bcbba"
                  #   #     value: 54.86
                  #   #   - color: "#20bf6b"
                  #   #     value: 59.9
                  #   #   - color: "#26de81"
                  #   #     value: 64.76
                  #   #   - color: "#fed330"
                  #   #     value: 69.8
                  #   #   - color: "#f7b731"
                  #   #     value: 74.84
                  #   #   - color: "#fd9644"
                  #   #     value: 79.88
                  #   #   - color: "#fa8231"
                  #   #     value: 84.74
                  #   #   - color: "#eb3b5a"
                  #   #     value: 96.62
                  #   group_by:
                  #     func: avg
                  #     duration: 30min
                  # - entity: sensor.air_temperature # Basement
                  #   type: line
                  #   name: Temperature
                  #   # color_threshold:
                  #   #   - color: "#a55eea"
                  #   #     value: 19.58
                  #   #   - color: "#8854d0"
                  #   #     value: 24.98
                  #   #   - color: "#3867d6"
                  #   #     value: 29.84
                  #   #   - color: "#4b7bec"
                  #   #     value: 34.88
                  #   #   - color: "#2d98da"
                  #   #     value: 39.74
                  #   #   - color: "#45aaf2"
                  #   #     value: 44.78
                  #   #   - color: "#0fb9b1"
                  #   #     value: 49.82
                  #   #   - color: "#2bcbba"
                  #   #     value: 54.86
                  #   #   - color: "#20bf6b"
                  #   #     value: 59.9
                  #   #   - color: "#26de81"
                  #   #     value: 64.76
                  #   #   - color: "#fed330"
                  #   #     value: 69.8
                  #   #   - color: "#f7b731"
                  #   #     value: 74.84
                  #   #   - color: "#fd9644"
                  #   #     value: 79.88
                  #   #   - color: "#fa8231"
                  #   #     value: 84.74
                  #   #   - color: "#eb3b5a"
                  #   #     value: 96.62
                  #   group_by:
                  #     func: avg
                  #     duration: 30min
                  # - entity: "[[humidity_entity]]"
                  #   type: column
                  #   name: Humidity
                  #   group_by:
                  #     func: avg
                  #     duration: 30min
                # - type: custom:decluttering-card
                #   template: graph_environment
                #   variables:
                #     - temperature_entity: sensor.multisensor_air_temperature_2
                #     - humidity_entity: sensor.multisensor_humidity_2
          - type: col
            class: "col-12 col-sm-12 col-md-6 col-lg-6"
            cards:
              - type: custom:homekit-card
                titleColor: "#fff"
                horizontalScroll: true
                statePositionTop: true
                useBrightness: false
                useTemperature: true
                enableColumns: true
                tileHoldAnimation: false
                panel: true
                home: false
                rows:
                  - row: 1
                    columns:
                      - column: 1
                        entities:
                          - entities:
                              - card: "custom:mini-graph-card"
                                cardOptions:
                                  entities:
                                    - entity: sensor.air_temperature
                                  show: ""
                                  labels: false
                                  color_thresholds:
                                    - value: -20
                                      color: "#008bff"
                                    - value: -10
                                      color: "#62d9ff"
                                    - value: -5
                                      color: "#a4f5ff"
                                    - value: 0
                                      color: "#f1ffff"
                                    - value: 5
                                      color: "#ffff88"
                                    - value: 10
                                      color: "#ffe359"
                                    - value: 15
                                      color: "#ffb92c"
                                    - value: 20
                                      color: "#ff9d20"
                                    - value: 25
                                      color: "#ff7d1d"
                                    - value: 30
                                      color: "#ff5d11"
                                    - value: 35
                                      color: "#ff3609"
                                    - value: 40
                                      color: "#a61e00"
                                  animate: true
                                  hours_to_show: 24
                                  points_per_hour: 1
                                  update_interval: 1
                                  line_color: var(--accent-color)
                                  line_width: 8
                                  font_size: 50
                                  aggregate_func: max
                                noPadding: true
                                higher: true
                                higherSize: 1
                                wider: true
                                widerSize: 2
                              - card: "custom:mini-graph-card"
                                show_state: true
                                cardOptions:
                                  entities:
                                    - entity: sensor.air_temperature
                                  show: ""
                                  labels: false
                                  color_thresholds:
                                    - value: -20
                                      color: "#008bff"
                                    - value: -10
                                      color: "#62d9ff"
                                    - value: -5
                                      color: "#a4f5ff"
                                    - value: 0
                                      color: "#f1ffff"
                                    - value: 5
                                      color: "#ffff88"
                                    - value: 10
                                      color: "#ffe359"
                                    - value: 15
                                      color: "#ffb92c"
                                    - value: 20
                                      color: "#ff9d20"
                                    - value: 25
                                      color: "#ff7d1d"
                                    - value: 30
                                      color: "#ff5d11"
                                    - value: 35
                                      color: "#ff3609"
                                    - value: 40
                                      color: "#a61e00"
                                  animate: true
                                  hours_to_show: 24
                                  points_per_hour: 1
                                  update_interval: 1
                                  line_color: var(--accent-color)
                                  line_width: 8
                                  font_size: 50
                                  aggregate_func: max
                                noPadding: true
                                higher: true
                                higherSize: 1
                                wider: true
                                widerSize: 2
                              - card: "custom:mini-graph-card"
                                cardOptions:
                                  entities:
                                    - entity: sensor.air_temperature
                                  show: ""
                                  labels: false
                                  color_thresholds:
                                    - value: -20
                                      color: "#008bff"
                                    - value: -10
                                      color: "#62d9ff"
                                    - value: -5
                                      color: "#a4f5ff"
                                    - value: 0
                                      color: "#f1ffff"
                                    - value: 5
                                      color: "#ffff88"
                                    - value: 10
                                      color: "#ffe359"
                                    - value: 15
                                      color: "#ffb92c"
                                    - value: 20
                                      color: "#ff9d20"
                                    - value: 25
                                      color: "#ff7d1d"
                                    - value: 30
                                      color: "#ff5d11"
                                    - value: 35
                                      color: "#ff3609"
                                    - value: 40
                                      color: "#a61e00"
                                  animate: true
                                  hours_to_show: 24
                                  points_per_hour: 1
                                  update_interval: 1
                                  line_color: var(--accent-color)
                                  line_width: 8
                                  font_size: 50
                                  aggregate_func: max
                                noPadding: true
                                higher: true
                                higherSize: 1
                                wider: true
                                widerSize: 2
                              - card: "custom:mini-graph-card"
                                cardOptions:
                                  entities:
                                    - entity: sensor.basement_temperature
                                  show: ""
                                  labels: false
                                  color_thresholds:
                                    - value: 0
                                      color: "#008bff"
                                    - value: 20
                                      color: "#62d9ff"
                                    - value: 40
                                      color: "#a4f5ff"
                                    - value: 60
                                      color: "#f1ffff"
                                    - value: 80
                                      color: "#ffff88"
                                    - value: 100
                                      color: "#ffe359"
                                    - value: 120
                                      color: "#ffb92c"
                                    - value: 140
                                      color: "#ff9d20"
                                    - value: 160
                                      color: "#ff7d1d"
                                    - value: 180
                                      color: "#ff5d11"
                                    - value: 200
                                      color: "#ff3609"
                                    - value: 250
                                      color: "#a61e00"
                                  animate: true
                                  hours_to_show: 24
                                  points_per_hour: 1
                                  update_interval: 1
                                  line_color: var(--accent-color)
                                  line_width: 8
                                  font_size: 50
                                  aggregate_func: max
                                noPadding: true
                                higher: true
                                higherSize: 1
                                wider: true
                                widerSize: 2
                            title: Temperature & AQI Status
