# Carbon Dioxide Levels and Your Health

#     250 – 350 ppm + background (normal) outdoor air level
#     350- 1,000 ppm – typical level found in occupied spaces with good air exchange.
#     1,000 – 2,000 ppm – level associated with complaints of drowsiness and poor
#     air.
#     2,000 – 5,000 ppm – level associated with headaches, sleepiness, and
#     stagnant, stale, stuffy air. Poor concentration, loss of attention, increased heart
#     rate and slight nausea may also be present.
#     >5,000 ppm – Exposure may lead to serious oxygen deprivation symptoms

# What are safe levels of CO and CO2 in rooms?
# Home » Knowledge Centre FAQs » What are safe levels of CO and CO2 in rooms?

# What are safe levels of CO and CO2 in rooms?
# CO2

# 250-400ppm 	Normal background concentration in outdoor ambient air
# 400-1,000ppm 	Concentrations typical of occupied indoor spaces with good air exchange
# 1,000-2,000ppm 	Complaints of drowsiness and poor air.
# 2,000-5,000 ppm 	Headaches, sleepiness and stagnant, stale, stuffy air. Poor concentration, loss of attention, increased heart rate and slight nausea may also be present.
# 5,000 	Workplace exposure limit (as 8-hour TWA) in most jurisdictions.
# >40,000 ppm 	Exposure may lead to serious oxygen deprivation resulting in permanent brain damage, coma, even death.
# CO

# 9 ppm 	CO Max prolonged exposure (ASHRAE standard)
# 35 ppm 	CO Max exposure for 8 hour work day (OSHA)
# 800 ppm 	CO Death within 2 to 3 hours
# 12,800 ppm 	CO Death within 1 to 3 minutes
# https://www.kane.co.uk/knowledge-centre/what-are-safe-levels-of-co-and-co2-in-rooms

# 250-400ppm 	Normal background concentration in outdoor ambient air
# 400-1,000ppm 	Concentrations typical of occupied indoor spaces with good air exchange
# 1,000-2,000ppm 	Complaints of drowsiness and poor air.
# 2,000-5,000 ppm 	Headaches, sleepiness and stagnant, stale, stuffy air. Poor concentration, loss of attention, increased heart rate and slight nausea may also be present.
# 5,000 	Workplace exposure limit (as 8-hour TWA) in most jurisdictions.

sensor:
  - platform: filter
    name: "Office1 Realistic co2"
    entity_id: sensor.bme680_co2_equivalent # sensor.bme680_breath_voc_equivalent
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2

template:
  - binary_sensor:
      - name: "Office1 co2 Status"
        device_class: "problem"
        state: >
          {{ states('sensor.bme680_co2_equivalent') | int <= 1000 }}
