############################################################
##                                                        ##
##                  Environmental Health                  ##
##                                                        ##
############################################################

# Automations
#
# - Alert if the humidity status changes beyond a given threshold.
#

sensor:
  - platform: filter
    name: "Bedroom1 Realistic Humidity"
    entity_id: sensor.motion_bedroom1_humidity
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2

- platform: min_max
  name: Area - Household Humidity
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.waqi_bangor_maine_usa

template:
  - binary_sensor:
      - name: "Bedroom1 Humidity Status"
        device_class: "problem"
        state: >
          {% set state = states('sensor.bedroom1_realistic_humidity') %}
          {{ is_number(state) and ( state | float < 40  or state | float > 50 )  }}
        delay_on: 00:00:30
        delay_off: 00:00:30
        attributes:
          room: "Bedroom 1"
          reason: >-
            {% set current_state = states('sensor.bedroom1_realistic_humidity')|int %}
            {% if current_state < 15 %}
              Way too dry
            {% elif current_state < 20 %}
              Too Dry
            {% elif current_state < 40 %}
              Dry
            {% elif current_state < 50 %}
              Good
            {% elif current_state < 60 %}
              Humid
            {% elif current_state < 65 %}
              Too Humid
            {% elif current_state < 80 %}
              Soaking
            {% else %}
              Saturation Point
            {% endif %}

      - name: "Livingroom1 Humidity Status"
        device_class: "problem"
        state: >
          {% set state = states('sensor.motion_frontroom_humidity') %}
          {{ is_number(state) and ( state | float < 40  or state | float > 50 )  }}
        delay_on: 00:00:30
        delay_off: 00:00:30
        attributes:
          room: "Livingroom 1"
          reason: >-
            {% set current_state = states('sensor.motion_frontroom_humidity')|int %}
            {% if current_state < 15 %}
              Way too dry
            {% elif current_state < 20 %}
              Too Dry
            {% elif current_state < 40 %}
              Dry
            {% elif current_state < 50 %}
              Good
            {% elif current_state < 60 %}
              Humid
            {% elif current_state < 65 %}
              Too Humid
            {% elif current_state < 80 %}
              Soaking
            {% else %}
              Saturation Point
            {% endif %}

automation:
  - alias: AirQ - Indoor Humidity Notifications
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.bedroom1_humidity_status
          - binary_sensor.bedroom2_humidity_status
          - binary_sensor.livingroom1_humidity_status
    action:
      - service: persistent_notification.create
        data:
          notification_id: "{{ trigger.entity_id }}"
          message: >
            The humidity in {{ state_attr(trigger.entity_id, 'room') }} is {{ state_attr(trigger.entity_id, 'reason') }}
      - service: notify.all
        data:
          notification_id: "{{ trigger.entity_id }}"
          message: >
            The humidity in the {{ state_attr(trigger.entity_id, 'room') }} is {{ state_attr(trigger.entity_id, 'reason') }}
