############################################################
##                                                        ##
##                  Environmental Health                  ##
##                                                        ##
############################################################

# Automations
#
# - Alert if the humidity status changes beyond a given threshold.
#

sensor:
  - platform: filter
    name: "Bedroom1 Realistic Humidity"
    entity_id: sensor.unit_1_bedroom_humidity
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2

template:
  - binary_sensor:
      - name: "Bedroom1 Humidity Status"
        device_class: "problem"
        state: >
          {{ states('sensor.bedroom1_realistic_humidity') | int < 40 or states('sensor.bedroom1_realistic_humidity') | int > 50 }}
        attributes:
          room: "Bedroom 1"
          reason: >-
            {% set current_state = states('sensor.bedroom1_realistic_humidity')|int %}
            {% if current_state < 15 %}
              Way too dry
            {% elif current_state < 20 %}
              Too Dry
            {% elif current_state < 40 %}
              Dry
            {% elif current_state < 50 %}
              Good
            {% elif current_state < 60 %}
              Humid
            {% elif current_state < 65 %}
              Too Humid
            {% elif current_state < 80 %}
              Soaking
            {% else %}
              Saturation Point
            {% endif %}

automation:
  - alias: AirQ - Indoor Humidity Notifications
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.bedroom1_humidity_status
          - binary_sensor.bedroom2_humidity_status
          - binary_sensor.livingroom1_humidity_status
    action:
      - service: persistent_notification.create
        data:
          notification_id: "{{ trigger.entity_id }}"
          message: >
            The humidity in {{ state_attr(trigger.entity_id, 'room') }} is {{ state_attr(trigger.entity_id, 'reason') }}
      - service: notify.all
        data:
          message: >
            The humidity in the {{ state_attr(trigger.entity_id, 'room') }} is {{ state_attr(trigger.entity_id, 'reason') }}
