blueprint:
  name: Lights Off
  description: Turn off lights when no one is around.
  domain: automation
  source_url: https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/motion_light.yaml
  input:
    occupancy_entity:
      name: Occupancy Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    light_target:
      name: Light
      selector:
        entity:
          domain: light
    no_motion_wait:
      name: Wait time
      description: Time in seconds to leave the light on after last motion is detected.
      default: 900
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: single
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input light_target
    to: "on"
    for:
      seconds: !input no_motion_wait

  # The following triggers allow the automation to kick off after a restart/automations reloaded.
  - platform: homeassistant
    event: start
  - platform: event
    event_type:
      - automation_reloaded

action:
  - choose:
      - alias: "If the light is still on, enter a loop."
        conditions:
          - condition: state
            entity_id: !input light_target
            state: "on"
        sequence:
          - alias: "Wait until the room is unoccupied or the light is off"
            repeat:
              while:
                - condition: state
                  entity_id: !input occupancy_entity
                  state: "on"
                - condition: state
                  entity_id: !input light_target
                  state: "on"
              sequence:
                - delay: "00:00:05" # 1 second seemed excessive.
          - service: light.turn_off
            entity_id: !input light_target
