id: "a9aa9111-010f-493d-b611-41ac66ee5e7e"
alias: Light Upstairs Bedroom
description: Turns on the loft light when Person3 is home and it's dark
trigger:
  - at: "21:00"
    platform: time
condition:
  - condition: state
    entity_id: !secret person3_entity
    state: home
action:
  - service: light.turn_on
    entity_id: light.loft_evening_lights
mode: single
