id: "eb941460-7f24-49f5-b0f6-d36b76912ee4"
alias: Light AutoOff Frontroom
description: ""
trigger:
  - platform: state
    entity_id: light.frontroom_ceiling
    to: "on"
    for:
      hours: 0
      minutes: 15
      seconds: 0
action:
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.unit1_frontroom_occupied
        to: "off"
  - service: light.turn_off
    entity_id: light.frontroom_ceiling
mode: single