id: 0040dae3-d3c6-4d0a-a521-cee688b144f9
alias: "Lights: Outside Lights off at Bedtime"
description: Turn off outside lights at 11pm if we're all home.
trigger:
  - platform: time
    at: "23:00"
condition:
  - condition: state
    entity_id: group.household
    state: home
action:
  - type: turn_off
    entity_id: light.light_outside_front
    domain: light
mode: single