id: "a8d9090d-b313-4fdd-8722-5d02bf181528"
alias: "Occupancy: Person 1 Room Location"
trigger:
  - platform: state
    entity_id:
      - sensor.stefanie_room_presence # Person 1
      - sensor.richard_room_presence # Person 2
      - sensor.jenn_room_presence # Person 3
  - platform: zone
    entity_id:
      - !secret person1_entity
    zone: zone.home
action:
  - service: input_select.select_option
    data:
      entity_id: "{{ 'input_select.' + trigger.entity_id[7:-14] + '_location' }}"
      option: >
        {% set h = states(trigger.entity_id) %}
        {% if h == 'unit2livingroom' %}
          Upstairs
        {% elif h == 'unit2Front' %}
          Upper Office
        {% elif h == 'unit1FrontRoom' %}
          Downstairs
        {% elif h == 'pi0-lower-back' %}
          Downstairs
        {% else %}
          {{ h }}
        {% endif %}
