id: '1610287003436'
alias: Turn on Rinnai for 60 minutes in the morning, if it's needed.
description: ''
trigger:
- type: temperature
  platform: device
  device_id: cdef6f1e39e632997cc0858679c07393
  entity_id: sensor.unit1_hallway_temperature_air
  domain: sensor
  below: 60
  for:
    hours: 0
    minutes: 5
    seconds: 0
condition:
- condition: time
  after: 05:45
  before: 07:00
action:
  - service: switch.turn_on
    entity_id: switch.unit1_backroom_rinnai
  - delay: '01:00:00'
  - service: switch.turn_off
    entity_id: switch.unit1_backroom_rinnai
mode: single
