id: "55bf64c2-cfbb-486f-9427-d16789510424"
alias: Unlock Frontdoor
description: ""
trigger:
  - platform: state
    entity_id: person.richard
    to: home
condition: []
action:
  - device_id: 67e1d656b7ce207ea19d0086a945886f
    domain: lock
    entity_id: lock.frontdoor
    type: unlock
mode: single
