id: "ups_discharging_conserve_power"
alias: "UPS Discharging - Conserve power"
trigger:
  - platform: state
    entity_id: sensor.cyberpower_status_data
    to: "OB DISCHRG"
    for:
      minutes: 5
action:
  - service: notify.admins
    data:
      title: Home Assistant
      message: "System on battery.  Sleeping NAS"
  # - service: switch.turn_off
  #   entity_id: switch.omv_nas
