homeassistant:
  customize:
    package.room_assistant:
      room_determination: &room_determination
        state: >
          {% set h = states(trigger.entity_id) %}
          {% if h == 'pi0-upper-office' %}
            Upstairs
          {% elif h == 'pi0-upper-back' %}
            Upstairs Kitchen
          {% elif h == 'pi4-audio-1' %}
            Downstairs
          {% elif h == 'pi0-lower-bedroom' %}
            Bedroom1
          {% else %}
            {{ h }}
          {% endif %}

template:
  - trigger:
      - platform: state
        entity_id:
          - sensor.4246807c524d46c58df145284816b8e1_100_1_room_presence
      - platform: zone
        entity_id: !secret person1_entity
        zone: zone.home
    sensor:
      - name: "Person1 Location"
        <<: *room_determination

  - trigger:
      - platform: state
        entity_id:
          - sensor.186ca552_d54b_417c_b812_9778b0252aa7_room_presence
      - platform: zone
        entity_id: !secret person2_entity
        zone: zone.home
    sensor:
      - name: "Person2 Location"
        <<: *room_determination

  - trigger:
      - platform: state
        entity_id:
          - sensor.df8d2ff3_980f_43df_ba53_7482bbf25627_room_presence
      - platform: zone
        entity_id: !secret person3_entity
        zone: zone.home
    sensor:
      - name: "Person3 Location"
        <<: *room_determination
