- alias: "AirQ - Automatic basement dehumidifier"
  initial_state: "on"
  description: "Switch the dehumidifier on if there is a mold risk in the basement."
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.basement_mold_status
  action:
    - if:
        - condition: state
          entity_id: binary_sensor.basement_mold_status
          state: "on"
      then:
        - service: switch.turn_on
          target:
            entity_id: switch.dehumidifier
      else:
        - service: switch.turn_off
          target:
            entity_id: switch.dehumidifier
  mode: single
