- alias: Sump - Turn Sump back on
  description: If the sump pump power switch is off, turn it back on.
  trigger:
    platform: state
    entity_id: switch.sumppump
    to: "off"
    for:
      minutes: 15
  action:
    - service: script.turn_on
      entity_id:
        - switch.sumppump
    - wait_template: "{{ is_state('switch.sumppump', 'on') }}"
      timeout: "00:01:00"
    - service: persistent_notification.create
      data:
        message: >
          Sump switch was off, it is now back on.
  mode: single
