binary_sensor:
  - platform: trend
    sensors:
      area_bathroom_humidity_trend:
        friendly_name: Area - Bathroom Humidity Trend
        entity_id: sensor.motion_bathroom_humidity
        sample_duration: 1200
        max_samples: 6
        min_gradient: 0.011
        device_class: moisture

  - platform: bayesian
    name: Area - Bathroom Occupied
    prior: 0.2083
    device_class: occupancy
    probability_threshold: 0.70
    observations:
      - platform: "state"
        entity_id: binary_sensor.area_bathroom_humidity_trend
        prob_given_true: 0.0768
        prob_given_false: 0.0020
        to_state: "on"
      - platform: "state"
        entity_id: binary_sensor.motion_bathroom_home_security_motion_detection
        prob_given_true: 0.6720
        prob_given_false: 0.0531
        to_state: "on"
      - platform: "state"
        entity_id: sensor.motion_bathroom_illuminance
        prob_given_true: 1.2048
        prob_given_false: 0.2853
        to_state: "on"

sensor:
  ## Area Entities
  - platform: history_stats
    name: Stats - Bathroom Bright
    entity_id: binary_sensor.area_bathroom_bright
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      days: 7
  - platform: history_stats
    name: Stats - Bathroom Humidity Trend
    entity_id: binary_sensor.area_bathroom_humidity_trend
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      days: 7
  - platform: history_stats
    name: Stats - Bathroom Occupied
    entity_id: binary_sensor.area_bathroom_occupied
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      days: 7
  - platform: history_stats
    name: Stats - Bathroom Temperature Trend
    entity_id: sensor.motion_bathroom_air_temperature
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      days: 7
  - platform: history_stats
    name: Stats - Bathroom Motion
    entity_id: binary_sensor.motion_bathroom_home_security_motion_detection
    state: "on"
    type: ratio
    end: "{{ now() }}"
    duration:
      days: 7
