#################################################################
#                                                               #
#                            Alarm                              #
#                                                               #
#################################################################
alarm_control_panel:
  platform: manual
  name: Home Alarm
  arming_time: 30
  delay_time: 20
  trigger_time: 4
  disarmed:
    trigger_time: 0
  armed_home:
    arming_time: 0
    delay_time: 0
  armed_night:
    arming_time: 0
    delay_time: 0

group:
  alarm_sensors:
    # Lower Floor DWS
    - binary_sensor.bathroom_window_access_control_window_door_is_open
    - binary_sensor.frontdoor_access_control_window_door_is_open
    - binary_sensor.frontdoor_access_control_window_door_is_open_2
    - binary_sensor.main_entrance_access_control_window_door_is_open

    # Lower Motion
    - binary_sensor.q_sensor_home_security_motion_detection
    - binary_sensor.motion_living_room_home_security_motion_detection
    - binary_sensor.frontdoor_motion_home_security_motion_detection
    - binary_sensor.motion_bedroom1_home_security_motion_detection
    - binary_sensor.unit_1_mudroom_motion

    # Upper Floor DWS
    #- binary_sensor.backdoor_access_control_window_door_is_open

    # Upper Motion
    - binary_sensor.multisensor_unit2_office_motion

  all_house_locks:
    - lock.backdoor_lock
    - lock.frontdoor

input_boolean:
  panic_mode:
    name: Panic Mode
    initial: off
    icon: mdi:shield-outline

  walkthrough_mode:
    name: Walkthrough Mode
    initial: Off
    icon: mdi:walk

template:
  - sensor:
      - name: "Alarm Sensors Unavailable"
        state: >-
          {{ states|
              selectattr('entity_id', 'in', state_attr('group.alarm_sensors', 'entity_id'))
            |selectattr('state', 'in', ['unavailable', 'unknown', 'none'])
            |list
            |count
          }}
        attributes:
          entities: >-
            {{ states|
                selectattr('entity_id', 'in', state_attr('group.alarm_sensors', 'entity_id'))
              |selectattr('state', 'in', ['unavailable', 'unknown', 'none'])
              |map(attribute='entity_id')
              |list
            }}

switch:
  - platform: template
    switches:
      panic_mode:
        value_template: "{{ is_state('input_boolean.panic_mode', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: input_boolean.panic_mode
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: input_boolean.panic_mode

automation:
  - id: alarm_arm_home_at_night
    alias: "Alarm: Arm Home at night"
    description: "Arms the alarm, and locks the doors"
    initial_state: "on"
    condition:
      - condition: state
        entity_id: group.household
        state: "home"
    trigger:
      platform: time
      at: "22:00:00"
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.home_alarm
      - service: lock.lock
        entity_id: group.all_house_locks

  - id: alarm_disarm_home
    alias: "Alarm: Disarm alarm in the morning if someone is home"
    trigger:
      platform: time
      at: "06:30:00"
    condition:
      - condition: state
        entity_id: group.household
        state: home
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.home_alarm

  - alias: Alarm - Panic Button On
    id: "alarm_panic_button_on"
    description: "Experimental: Panic button."
    trigger:
      - platform: state
        entity_id: switch.panic_mode
        to: "on"
    action:
      - service: notify.admins
        data:
          message: Panic Button Has Been Pressed!
          data:
            apns_headers:
            "apns-collapse-id": "security-alarm"
            push:
              badge: 0
              category: "alarm"
              sound:
                name: default
                critical: 1
                volume: 1.0

  - alias: Alarm - Panic Button Off
    id: "alarm_panic_button_off"
    trigger:
      - platform: state
        entity_id: switch.panic_mode
        to: "off"
    action:
      - service: switch.turn_off
        entity_id:
          - switch.siren

  - alias: Alarm - Panic Button Auto Off
    id: "alarm_panic_button_auto_off"
    trigger:
      - platform: state
        entity_id: switch.panic_mode
        to: "on"
        for:
          hours: 0
          minutes: 2
          seconds: 0
    action:
      - service: switch.turn_off
        entity_id:
          - switch.siren

  - id: alarm_armed_away
    alias: Alarm State Changed
    trigger:
      platform: state
      entity_id: alarm_control_panel.home_alarm
    action:
      data_template:
        title: Home alarm state
        message:
          "{% if trigger.to_state.state == 'arming' %}\n    Alarm is arming,\
          \ please exit the building!\n{%- else -%}\n    Alarm has been set to: {{ trigger.to_state.state|replace(\"\
          armed_\", \"\")|title }}\n{%- endif %}\n"
      service: notify.all

  - alias: "Alarm: Trigger alarm while armed away"
    trigger:
      - platform: state
        entity_id: group.alarm_sensors
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    action:
      service: alarm_control_panel.alarm_trigger
      target:
        entity_id: alarm_control_panel.home_alarm

  - alias: "Alarm: Send notification when alarm triggered"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "triggered"
    action:
      - service: notify.all
        data:
          title: Home Alarm
        data_template:
          message: "Alarm! {{ trigger.to_state.attributes.friendly_name }} has triggered the alarm."

  - id: "1630716542865"
    alias: "Alarm: Sensors unavailable"
    trigger:
      - platform: state
        entity_id: sensor.alarm_sensors_unavailable
    action:
      - choose:
          conditions:
            - condition: numeric_state
              entity_id: sensor.alarm_sensors_unavailable
              below: 1
          sequence:
            - service: persistent_notification.dismiss
              data:
                notification_id: unavailable_entities
        default:
          - service: persistent_notification.create
            data:
              title: Unavailable Entities
              message: "- {{ expand(state_attr('sensor.alarm_sensors_unavailable','entities'))|map(attribute='entity_id')|join('\n- ') }}"
              notification_id: unavailable_entities

  - id: "1630716542863"
    alias: "Alarm: Sensor Walkthrough Test State"
    trigger:
      platform: state
      entity_id: input_boolean.walkthrough_mode
    action:
      - service: tts.cloud_say
        data:
          entity_id: media_player.multi_room_controller
          message: >
            {% if trigger.to_state.state == 'on' %}
              Walkthrough Mode Activated
            {% else %}
              Walkthrough Mode Disabled
            {% endif %}
    mode: single

  - id: "1630716542864"
    alias: "Alarm: Sensor Walkthrough Test"
    trigger:
      - platform: state
        entity_id: binary_sensor.unit_1_bedroom_motion
        id: unit1_bedroom
        to: "on"
      - platform: state
        entity_id: binary_sensor.unit_1_mudroom_motion
        id: unit1_mudroom
        to: "on"
      - platform: state
        entity_id: binary_sensor.motion_bathroom_home_security_motion_detection
        id: unit1_bathroom
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.walkthrough_mode
        state: "on"
    action:
      - service: tts.cloud_say
        data:
          entity_id: media_player.multi_room_controller
          message: >
            Motion in {{ trigger.id|replace('_', ' ') }} Detected
    mode: single
