binary_sensor:
  - platform: workday
    name: Workday Today
    country: !secret country
    province: !secret province

  - platform: workday
    name: Workday Tomorrow
    country: !secret country
    province: !secret province
    days_offset: 1

  - platform: tod
    name: evening
    after: sunset
    after_offset: "-00:30"
    before: "23:59"

  - platform: tod
    name: night
    after: "23:59"
    before: "05:30"

  - platform: ping
    host: www.github.com
    name: WAN
    scan_interval: 60

  - platform: ping
    host: 192.168.10.1
    name: Gateway
    scan_interval: 60

  - platform: template
    sensors:
      disable_bedroom1_motion_lights:
        friendly_name: "Disable Bedroom1 Motion Lights"
        value_template: >
          {{ is_state('input_boolean.guests', 'on') or is_state('input_boolean.bedtime', 'on') }}

      disable_backroom_motion_lights:
        friendly_name: "Disable Backroom Motion Lights"
        value_template: >
          {{ is_state('input_boolean.guests', 'on') or is_state('input_boolean.bedtime', 'on') }}

      disable_frontroom_motion_lights:
        friendly_name: "Disable Front Motion Lights"
        value_template: >
          {{ is_state('input_boolean.guests', 'on') or is_state('input_boolean.bedtime', 'on') }}
