---
###################################################
#                                                 #
#                  Lights                         #
#                                                 #
###################################################

light:
  - platform: group
    name: Outside
    entities:
      - light.light_outside_front
      - light.outside_light
      - light.unit2_deck_lights_dimmer
      - light.deck_lights

  - platform: group
    name: Downstairs
    entities:
      - light.bedroom1
      - light.person1_nightlight
      - light.person2_nightlight
      - light.unit1_hallway_lights
      - light.unit1_kitchen_ceiling_light
      - light.unit1_kitchen_cabinets
      - light.downstairs_backroom
      - light.unit1_livingroom_lamp
      - light.frontroom_ceiling
      - light.switches_bathroom1
      - light.unit1_bathroom_ceiling
      - light.switches_mudroom
      - light.lower_back_deck_light

  - platform: group
    name: Upstairs
    entities:
      - light.unit2_loft_light_dimmer
      - light.unit2_loft_fairy_lights
      - light.upstairs_kitchen_pendants
      - light.upstairs_kitchen_spotlights
      - light.upstairs_fireside_lamp
      - light.upper_livingroom_lamp
      - light.staircase_lights
      - light.unit2_sofa_lamp
      - light.unit2_office

  - platform: group
    name: Loft Lights
    entities:
      - light.unit2_loft_fairy_lights

  - platform: group
    name: Unit1 Bathroom Lights
    entities:
      - light.unit1_bathroom_vanity_light
      - light.bathroom_shower_light # wtf?

  - platform: group
    name: Unit1 Kitchen Lights
    entities:
      - light.unit1_hallway_lights
      - light.unit1_kitchen_ceiling_light
      - light.unit1_kitchen_cabinets
      - light.unit1_kitchen_pendants

  - platform: group
    name: Unit1 Bedroom Lights
    entities:
      - light.person1_nightlight
      - light.person2_nightlight
      - light.unit1_light_bedroom_dimmer

  - platform: group
    name: Unit1 Livingroom Lights
    entities:
      - light.unit1_light_livingroom_dimmer
      - light.unit1_livingroom_lamp

  #
  # Pseudo-lights that are actually switches
  #
  - platform: switch
    name: Person2 Nightlight
    entity_id: switch.bedroom_switches_2_2

  - platform: switch
    name: Person1 Nightlight
    entity_id: switch.bedroom_switches_2

  - platform: switch
    name: Unit1 Livingroom Lamp
    entity_id: switch.light_end_table

  - platform: switch
    name: Unit1 Kitchen Ceiling Light
    entity_id: switch.kitchen_ceiling_lights

  - platform: switch
    name: Unit1 Kitchen Pendants
    entity_id: switch.kitchen_pendants

  - platform: switch
    name: Unit1 Kitchen Cabinets
    entity_id: switch.cabinet_lights

  - platform: switch
    name: Unit1 Hallway Lights
    entity_id: switch.hallway_lights

  - platform: switch
    name: Unit1 Bathroom Ceiling
    entity_id: switch.switches_bathroom1

  - platform: switch
    name: Unit1 Bathroom Vanity Light
    entity_id: switch.unit1_bathroom_vanity_light

  - platform: switch
    name: Unit1 Bathroom Shower Light
    entity_id: switch.unit1_bathroom_shower_light

  - platform: switch
    name: Lower back deck light
    entity_id: switch.switches_mudroom

    #
    # Upstairs Lights
    #
  - platform: group
    name: Loft Evening Lights
    entities:
      - light.unit2_loft_light_dimmer
      - light.unit2_loft_fairy_lights

  - platform: group
    name: Upstairs Livingroom
    entities:
      - light.unit2_sofa_lamp
      - light.upper_livingroom_lamp

  - platform: group
    name: Upstairs Kitchen
    entities:
      - light.upstairs_kitchen_pendants
      - light.upstairs_kitchen_spotlights

  - platform: switch
    name: "Unit2 Loft Fairy Lights"
    entity_id: switch.unit2_socket_bedroom

  - platform: switch
    name: "Office Light"
    entity_id: switch.unit2_office_switch

  - platform: switch
    name: "Upstairs Fireside Lamp"
    entity_id: switch.unit2livingroomsocket

  - platform: switch
    name: "Staircase Lights"
    entity_id: switch.staircase_lights

  - platform: switch
    name: "Unit2 Sofa Lamp"
    entity_id: switch.unit2_socket_livingroom_couch_2

  - platform: switch
    name: Bathroom2 Vanity
    entity_id: switch.light_bathroom2

input_number:
  unit1_frontroom_lights_off_duration:
    icon: mdi:clock-start
    initial: 15
    min: 1
    max: 1440

  room_light_level:
    min: 1
    max: 1440

  bathroom2_off_duration:
    icon: mdi:clock-start
    initial: 5
    min: 1
    max: 1440

powercalc:

#
# For energy monitoring
#
sensor:
  - platform: powercalc
    entity_id: light.frontroom_ceiling
    fixed:
      power: 36
