##    input_select.house_presence – keeps track of who is home
##    input_select.*room*_presence – keeps track of individual room presence
##    input_select.*person*_location – keeps track of where people are (and is more detailed than the home/away person.*person* entity)

input_boolean:
  guests:
    initial: off

homeassistant:
  customize:
    package.occupancy:
      room_determination: &room_determination
        state: >
          {% set h = states(trigger.entity_id) %}
          {% if h == 'unit2livingroom' %}
            Upstairs
          {% elif h == 'unit1FrontRoom' %}
            Downstairs
          {% elif h == 'not_home' %}
            {% set away_for = ((as_timestamp(now()) - as_timestamp(states.sensor[trigger.entity_id].last_changed)) /60) |int %}
            {{ away_for }}
            {% if (away_for <= 1) %}
              Just Left
            {% elif away_for <= 1440 %}
              Away
            {% else %}
              Extended Away
            {% endif %}
          {% else %}
            Bathroom
          {% endif %}

      occupancy_states: &occupancy_states
        options:
          - Unknown
          - Empty
          - Someone
          - Guests
          - Extended Away

      location_states: &location_states
        options:
          - Unknown
          - Just Arrived
          - Home
          - Just Left
          - Away
          - Extended Away
          - Unit1 Kitchen
          - Unit1 Livingroom
          - Unit2 Livingroom
          - Bedroom
          - Bathroom
          - Upper Office

binary_sensor:
  - platform: template
    sensors:
      main_floor_occupancy:
        friendly_name: "Ground floor occupied"
        device_class: "occupancy"
        delay_off:
          minutes: 5
        delay_on:
          seconds: 3
        value_template: >-
          {{ (is_state('input_boolean.home_occupied', 'on') 
              and (
                   is_state('binary_sensor.bedroom1_occupied', 'on')) 
                or is_state('binary_sensor.unit1_frontroom_occupied', 'on')
              )
          }}

      bedroom1_occupied:
        friendly_name: "Bedroom1 Occupancy"
        device_class: "occupancy"
        delay_off:
          minutes: 5
        value_template: >-
          {{ is_state('binary_sensor.unit_1_bedroom_motion', 'on' )}}

      unit1_frontroom_occupied:
        friendly_name: "Living Room Occupancy"
        device_class: "occupancy"
        delay_off:
          minutes: 5
        delay_on:
          seconds: 3
        value_template: >-
          {{ is_state('media_player.50_tcl_roku_tv', 'playing')
                or is_state('media_player.50_tcl_roku_tv', 'on')
                or is_state('binary_sensor.q_sensor_home_security_motion_detection', 'on')
                or is_state('sensor.c3dcc47c1745_room_presence', 'unit1FrontRoom')
          }}

      unit1_backroom_occupancy:
        friendly_name: "Back Room Occupancy"
        device_class: "occupancy"
        delay_off:
          minutes: 5
        delay_on:
          seconds: 3
        value_template: >-
          {{ is_state('binary_sensor.motion_living_room_home_security_motion_detection', 'on') 
              or is_state('sensor.4246807c524d46c58df145284816b8e1_100_1_room_presence', 'unit1BackPi')
              or is_state('sensor.186ca552_d54b_417c_b812_9778b0252aa7_room_presence', 'unit1BackPi')
              or is_state('sensor.df8d2ff3_980f_43df_ba53_7482bbf25627_room_presence', 'unit1BackPi')
          }}

      bathroom_generic_presence:
        friendly_name: "Bathroom occupied"
        device_class: "occupancy"
        delay_off:
          minutes: 5
        value_template: >-
          {{ is_state('binary_sensor.motion_bathroom_home_security_motion_detection', 'on') }}

      #
      # First Floor
      #
      first_floor_occupancy:
        friendly_name: "First floor occupancy"
        device_class: "occupancy"
        delay_off:
          minutes: 5
        delay_on:
          seconds: 3
        value_template: >-
          {{ (is_state('input_boolean.home_occupied', 'on') 
                and (
                     is_state('binary_sensor.first_floor_bathroom_occupancy', 'on')
                  or is_state('binary_sensor.unit2_livingroom_occupancy', 'on')
                  or is_state('sensor.richard_location', 'Upstairs')
                ))
          }}

      first_floor_bathroom_occupancy:
        friendly_name: "Bathroom2 occupied"
        device_class: "occupancy"
        delay_off:
          minutes: 5
        value_template: >-
          {{ is_state('binary_sensor.motion_bathroom2_home_security_motion_detection', 'on') }}

      unit2_livingroom_occupancy:
        friendly_name: "Upper Living Room Occupancy"
        device_class: "occupancy"
        delay_off:
          minutes: 5
        delay_on:
          seconds: 3
        value_template: >-
          {{ is_state('binary_sensor.first_floor_occupancy', 'on')           
              and is_state('media_player.roku_streaming_stick', 'playing')
            }}

  - platform: template
    sensors:
      office_computer_on:
        value_template: "{{ states('sensor.office_power_electricity_w_meter') | int > 40 }}"

  - platform: template
    sensors:
      unit2_office_occupancy:
        friendly_name: "Unit2 Office Occupied"
        device_class: "occupancy"
        delay_off:
          minutes: 5
        delay_on:
          seconds: 3
        value_template: >-
          {{ (is_state('input_boolean.home_occupied', 'on')
             and is_state('binary_sensor.unit_1_experiment_rcwl0516_movement', 'on')) }}

group:
  person_home_away:
    name: Person Locations
    entities:
      - person.richard
      - person.stefanie
      - person.jenn

input_select:
  house_presence:
    name: Home Presence
    initial: Unknown
    <<: *occupancy_states

template:
  - trigger:
      - platform: state
        entity_id:
          - sensor.4246807c524d46c58df145284816b8e1_100_1_room_presence
    sensor:
      - name: "Person1 Location"
        <<: *room_determination

  - trigger:
      - platform: state
        entity_id:
          - sensor.186ca552_d54b_417c_b812_9778b0252aa7_room_presence
    sensor:
      - name: "Person2 Location"
        <<: *room_determination

  - trigger:
      - platform: state
        entity_id:
          - sensor.df8d2ff3_980f_43df_ba53_7482bbf25627_room_presence
    sensor:
      - name: "Person3 Location"
        <<: *room_determination

automation:
  - id: "37f15be9-acd5-49db-bdad-ddd5ce35ac2a"
    alias: "Set home to occupied"
    trigger:
      platform: state
      entity_id:
        - person.richard
        - person.stefanie
        - person.jenn
      to: home
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.home_occupied

  - id: "04bd834f-d3ac-4e45-a440-807fc26d5d39"
    alias: "Set home to not occupied"
    trigger:
      platform: state
      entity_id:
        - person.richard
        - person.stefanie
        - person.jenn
      from: home
      to: not_home
      for:
        minutes: 5
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: person.richard
          state: not_home
        - condition: state
          entity_id: person.stefanie
          state: not_home
        - condition: state
          entity_id: person.jenn
          state: not_home
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.home_occupied

  - id: "0d759a38-f0c8-4897-9255-10122b40f16c"
    alias: "Away Status: Extended Away"
    trigger:
      platform: state
      entity_id:
        - person.richard
        - person.stefanie
        - person.jenn
      to: not_home
      for:
        hours: 24
    action:
      - service: input_select.select_option
        data:
          entity_id: "{{ 'input_select.' + trigger.entity_id[7:] + '_loctation' }}"
          option: "Extended Away"

  - id: "a7294d7b-ffe0-4a59-8e72-a15be47463ec"
    alias: "Away Status: Leaving"
    trigger:
      platform: state
      entity_id:
        - person.richard
        - person.stefanie
        - person.jenn
      to: not_home
    action:
      - service: input_select.select_option
        data:
          entity_id: "{{ 'input_select.' + trigger.entity_id[7:] + '_location' }}"
          option: "Just Left"
      - service: tts.cloud_say
        data:
          entity_id: media_player.multi_room_controller
          message: >
            {{ trigger.entity_id[7:] }} has just left.
      - delay:
          minutes: 1
      - service: input_select.select_option
        data:
          entity_id: "{{ 'input_select.' + trigger.entity_id[7:] + '_location' }}"
          option: "Away"
      - service: tts.cloud_say
        data:
          entity_id: media_player.multi_room_controller
          message: >
            {{ trigger.entity_id[7:] }} is now away.
    mode: parallel

  - id: "231ea913-dde3-495e-aa9f-3817671010b6"
    alias: "Away Status: Arriving"
    trigger:
      platform: state
      entity_id:
        - person.richard
        - person.stefanie
        - person.jenn
      to: home
    action:
      - service: input_select.select_option
        data:
          entity_id: "{{ 'input_select.' + trigger.entity_id[7:] + '_location' }}"
          option: "Just Arrived"
      - service: tts.cloud_say
        data:
          entity_id: media_player.multi_room_controller
          message: >
            {{ trigger.entity_id[7:] }} has just arrived.
      - delay:
          minutes: 1
      - service: input_select.select_option
        data:
          entity_id: "{{ 'input_select.' + trigger.entity_id[7:] + '_location' }}"
          option: "Home"

  - id: "f2f4f55f-d1a5-4e06-91f0-0dfce4292b69"
    alias: "Room Location"
    trigger:
      platform: state
      entity_id:
        - sensor.df8d2ff3_980f_43df_ba53_7482bbf25627_room_presence
      to: "unit2livingroom"
      for:
        minutes: 2
    action:
      - service: tts.cloud_say
        data:
          entity_id: media_player.multi_room_controller
          message: >
            {{ trigger.entity_id[7:] }} is in the upper living room.

  - id: "be3a7395-ef91-48b6-b8a2-547a5cc1b164"
    alias: "Room Location: Richard"
    trigger:
      platform: state
      entity_id: sensor.186ca552_d54b_417c_b812_9778b0252aa7_room_presence
      to: "unit2Front"
      for:
        minutes: 2
    action:
      - service: tts.cloud_say
        data:
          entity_id: media_player.multi_room_controller
          message: >
            {% if ((now() - states.binary_sensor.motion_living_room_home_security_motion_detection.last_changed).seconds < 60 ) %}
              Richard is in the living room
            {% else %}
              Richard is in the office
            {% endif %}
