##    input_select.house_presence – keeps track of who is home
##    input_select.*room*_presence – keeps track of individual room presence
##    input_select.*person*_location – keeps track of where people are (and is more detailed than the home/away person.*person* entity)

homeassistant:
  customize:
    package.occupancy:
      room_determination: &room_determination
        state: >
          {% set h = states(trigger.entity_id) %}
          {% if h == 'unit2livingroom' %}
            Upstairs
          {% elif h == 'unit2Front' %}
            Office
          {% elif h == 'unit1FrontRoom' %}
            Downstairs
          {% else %}
            {{ h }}
          {% endif %}

      occupancy_states: &occupancy_states
        options:
          - Unknown
          - Empty
          - Someone
          - Guests
          - Extended Away

      location_states: &location_states
        options:
          - Unknown
          - Just Arrived
          - Home
          - Just Left
          - Away
          - Extended Away
          - Kitchen
          - Downstairs
          - Upstairs
          - Downstairs Livingroom
          - Upstairs Livingroom
          - Bedroom
          - Bathroom
          - Upper Office

binary_sensor:
  - platform: template
    sensors:
      office_computer_on:
        value_template: "{{ states('sensor.office_power_electricity_w_meter') | int > 40 }}"

group:
  person_home_away:
    name: Person Locations
    entities:
      - person.richard
      - person.stefanie
      - person.jenn

input_select:
  house_presence:
    name: Home Presence
    initial: Unknown
    <<: *occupancy_states

  stefanie_location:
    <<: *location_states

  richard_location:
    <<: *location_states

  jenn_location:
    <<: *location_states

template:
  - trigger:
      - platform: state
        entity_id:
          - sensor.4246807c524d46c58df145284816b8e1_100_1_room_presence
      - platform: zone
        entity_id: !secret person1_entity
        zone: zone.home
    sensor:
      - name: "Person1 Location"
        <<: *room_determination

  - trigger:
      - platform: state
        entity_id:
          - sensor.186ca552_d54b_417c_b812_9778b0252aa7_room_presence
      - platform: zone
        entity_id: !secret person2_entity
        zone: zone.home
    sensor:
      - name: "Person2 Location"
        <<: *room_determination

  - trigger:
      - platform: state
        entity_id:
          - sensor.df8d2ff3_980f_43df_ba53_7482bbf25627_room_presence
      - platform: zone
        entity_id: !secret person3_entity
        zone: zone.home
    sensor:
      - name: "Person3 Location"
        <<: *room_determination
