#################################################################
#                                                               #
#                        Power Monitoring                       #
#                                                               #
#################################################################
utility_meter:
  energy_total_usage_daily:
    source: sensor.energy_total_usage
    cycle: daily

  weekly_total:
    source: sensor.energy_total_usage
    cycle: weekly

  monthly_total:
    source: sensor.energy_total_usage
    cycle: monthly

  energy_total_usage_monthly:
    source: sensor.energy_total_usage
    cycle: monthly

  # Basement
  daily_dehumidifier:
    source: sensor.dehumidifier_energy
    cycle: daily

  monthly_dehumidifier:
    source: sensor.dehumidifier_energy
    cycle: monthly

  # HomeLab
  daily_office:
    source: sensor.office_power_electricity_w_meter
    cycle: daily

  monthly_office:
    source: sensor.office_power_electricity_w_meter
    cycle: monthly

sensor:
  - platform: template
    sensors:
      energy_total_usage:
        friendly_name: Total Energy Usage
        unit_of_measurement: kWh
        value_template: "{{ (states('sensor.dehumidifier_energy')|float + states('sensor.office_power_electricity_w_meter')|float(default=0))|round(1) }}"
