homeassistant:
  customize_glob:
    sensor.*_power_yearly_kwh:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: energy
      state_class: measurement
    sensor.*_power_yearly:
      last_reset: "1970-01-01T00:00:00+00:00"
      device_class: energy
      state_class: measurement

utility_meter:
  imported_power_yearly:
    source: sensor.solaredge_imported_energy
    cycle: yearly
  exported_power_yearly:
    source: sensor.solaredge_exported_energy
    cycle: yearly

template:
  - sensor:
      - name: "Imported Power Yearly kWh"
        unique_id: imported_power_yearly_kwh
        state_class: measurement
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{(states('sensor.imported_power_yearly') | float) / 1000}}"
      - name: "Exported Power Yearly kWh"
        unique_id: exported_power_yearly_kwh
        state_class: measurement
        device_class: energy
        unit_of_measurement: "kWh"
        state: "{{(states('sensor.exported_power_yearly') | float) / 1000}}"
