#################################################################
#                                                               #
#                           Sump Pump                           #
#                                                               #
#################################################################
binary_sensor:
  - platform: template
    sensors:
      # When the Sump is running the power will spike above 5.
      main_pump_status:
        friendly_name: 'Main Pump Status'
        value_template: >
          {{ states('sensor.dehumidifer_power')|float > 5 }}

sensor:
  - platform: history_stats
    name: Main Pump 3day Cycles
    entity_id: binary_sensor.main_pump_status
    state: 'on'
    type: count
    end: '{{ now() }}'
    duration:
      days: 3
  
  - platform: history_stats
    name: Main Pump 30day Cycles
    entity_id: binary_sensor.main_pump_status
    state: 'on'
    type: count
    end: '{{ now().replace(minute=0).replace(second=0) }}'
    duration:
      days: 30
  
  - platform: history_stats
    name: Backup Pump 1day Cycles
    entity_id: binary_sensor.backup_pump_status
    state: 'on'
    type: count
    end: '{{ now().replace(minute=0).replace(second=0) }}'
    duration:
      days: 1

  - platform: history_stats
    name: Main Pump Running
    entity_id: binary_sensor.main_pump_status
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

# https://en.wikipedia.org/wiki/Total_dynamic_head
# Performance Curve
#  Height   Gallons
#  5  (1.5) 43 (163)
#  10 (3.0) 34 (129)
#  15 (4.0) 19 (72)
#
#
# https://www.zoellerpumps.com/en-ea/products/sump-effluent-pumps/residential/50-series#technical-data
# 10^3/hr
# 
#
# Sump Volume
# float sumpvolumeg = 17.17;  // (Pi*sumpPitRadius*sumpPitRadius*sumpPitHeightDraw)/ 0.000264172 

        # if (cycletime > 1) {
        #         addvolume = (sumpvolumeg / cycletime) * runseconds;  // how much water is being added per second
        #       } 
        #       totalgalpumped = addvolume + sumpvolumeg;
        #       pamps = x; // assign ct_clamp amp reading

automation:
  - alias: Sump may not be working
    description: If the sump pump has not run for a couple of days, set a notification.
    trigger:
      platform: numeric_state
      entity_id:
        - sensor.main_pump_3day_cycles
      below: 3
      for:
        minutes: 5
    action:
      service: persistent_notification.create
      data:
        message: >
          {{ trigger.to_state.name }} has not been running for a few days!
    mode: single

  - alias: Turn Sump back on
    description: If the sump pump power switch is off, turn it back on.
    trigger:
      platform: state
      entity_id: switch.dehumidifer
      to: 'off'
      for:
        minutes: 15
    action:
      - service: script.turn_on
        entity_id:
          - switch.dehumidifer
      - wait_template: "{{ is_state('switch.dehumidifer', 'on') }}"
        timeout: '00:01:00'
    mode: single