#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

group:
  core network:
    name: Core Network
    #view: no
    entities:
      - binary_sensor.core_router

  internet:
    name: Internet
    #view: no
    entities:
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload

  resources:
    name: RPi Resources
    #view: no
    entities:
      - sensor.disk_use
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.cpu_temperature
      - sensor.last_boot

  pi_hole:
    name: Pi Hole Status
    entities:
      # - sensor.pi_hole_status
      - switch.pi_hole
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_ads_percentage_blocked_today
      - sensor.pi_hole_dns_queries_cached
      - sensor.pi_hole_dns_queries_forwarded
      - sensor.pi_hole_dns_queries_today
      - sensor.pi_hole_dns_unique_clients
      - sensor.pi_hole_dns_unique_domains
      - sensor.pi_hole_domains_blocked

updater:
  include_used_components: true

counter:
  syslog_errors:
    name: "Errors in SysLog since start"
    initial: 0
    step: 1
    restore: false
    icon: mdi:alert

  syslog_warnings:
    name: "Warnings in SysLog since start"
    initial: 0
    step: 1
    restore: false
    icon: mdi:alert-outline

#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################
sensor:
  #
  # System Monitor
  #
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: "/"
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
  #
  # Version
  #
  # @link https://www.home-assistant.io/integrations/version/
  #
  - platform: version

  #
  # Friendly version report
  #
  # Useful for HADashboard.
  #
  # @see /appdaemon/dashboards/Status.dash
  #
  - platform: template
    sensors:
      version:
        friendly_name: Version
        friendly_name_template: >-
          {% if states('binary_sensor.updater') == 'on' %}
            Update Available
          {% else %}
            Version Installed
          {% endif %}
        icon_template: >-
          {% if states('binary_sensor.updater') == 'on' %}
            mdi:update
          {% else %}
            mdi:home-assistant
          {% endif %}
        value_template: >-
          {% set update = states('binary_sensor.updater') %}
          {% set version = state_attr('binary_sensor.updater', 'newest_version') %}
          {% if update == 'on' and version != None %}
            {{ version }}
          {% else %}
            {{ states('sensor.current_version') }}
          {% endif %}
        attribute_templates:
          current_version: >-
            {{ states('sensor.current_version') }}
          newest_version: >-
            {{ state_attr('binary_sensor.updater', 'newest_version') }}
          release_notes: >-
            {{ state_attr('binary_sensor.updater', 'release_notes') }}
          release_notes_html: >-
            {% set release_notes = state_attr('binary_sensor.updater', 'release_notes') %}
            {% if release_notes != None %}
              <a href="{{ release_notes }}" target="_new" style="color:var(--secondary-text-color);">Release notes</a>
            {% endif %}

  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ (value | multiply(0.001)) | round(1) }}"

  - platform: command_line
    name: YAML Code Lines Count
    command: find . -name '*.yaml' -not -path "./custom_components/*" -type f -print0 | xargs -0 cat | sed '/^\s*#/d;/^\s*$/d' | wc -l
    scan_interval: 14400
    unit_of_measurement: lines

  - platform: command_line
    name: ERRORS in System Log [command line]
    command: grep -c -E "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} ERROR .*$" /config/home-assistant.log || true
    scan_interval: 3600
    unit_of_measurement: pc

  - platform: command_line
    name: WARNINGS in System Log [command line]
    command: >
      grep -E "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} WARNING .*$" /config/home-assistant.log |
      grep -c -v -E "^.+ We found a custom integration .+ which has not been tested by Home Assistant.+$" || true
    scan_interval: 3600
    unit_of_measurement: pc

switch:
  - platform: template
    switches:
      pi_hole:
        value_template: "{{ is_state('binary_sensor.pi_hole_status', 'on') }}"
        turn_on:
          service: pi_hole.enable
        turn_off:
          service: pi_hole.disable
          data:
            duration: 00:00:60

#################################################################
#                                                               #
#                         System Health                         #
#                                                               #
#################################################################

system_health:

input_boolean:
  homeautomation:
    name: Home Automation
    icon: mdi:home-automation

#################################################################
#                                                               #
#                            Alerts                             #
#                                                               #
#################################################################
alert:
  home_automation:
    name: Home automation is disabled
    done_message: Home automation enabled
    entity_id: input_boolean.homeautomation
    state: "off"
    repeat: 30
    can_acknowledge: True
    #skip_first: True
    notifiers:
      - home_automation

#################################################################
#                                                               #
#                          Automations                          #
#                                                               #
#################################################################
automation:
  - id: update_verify
    alias: "Update VERIFY"
    trigger:
      # When Home Assistant starts.
      - platform: homeassistant
        event: start
      # Every 6 hours.
      - platform: time_pattern
        hours: "/6"
        minutes: 00
    action:
      # Wait a while so that everything is ready.
      - delay: 30
      # Force a refresh of the updater component.
      - service: homeassistant.update_entity
        entity_id: binary_sensor.updater

  ## Notify if we're running out of disk space on the main home-assistant server.
  - alias: Disk Use Alarm
    initial_state: "on"
    trigger:
      platform: numeric_state
      entity_id: sensor.disk_use
      above: 12
    action:
      - service: notify.admins
        data:
          title: "HA HASSIO Server"
          message: "Warning - HA Server Disk Use is {{states.sensor.disk_use.state}}Gb"

  ## Notify of High CPU Usage
  - alias: CPU Use Alarm
    initial_state: "on"
    trigger:
      platform: numeric_state
      entity_id: sensor.processor_use
      above: 85
    action:
      - service: notify.admins
        data:
          title: "HA HASSIO Server"
          message: "Warning - HA Server Processor {{states.sensor.processor_use.state}}%"

  ## Notify if CPU Temperature is High
  - alias: CPU Temp Alarm
    initial_state: "on"
    trigger:
      platform: numeric_state
      entity_id: sensor.cpu_temperature
      above: 85
    action:
      - service: notify.admins
        data:
          title: "HA HASSIO Server"
          message: "Warning - HA Server CPU Temp is {{states.sensor.cpu_temperature.state}}c"

  - alias: "HASS: ERRORs in System Log - Counter"
    id: 3b8230a5-49d5-437b-8bd9-d3f72f95425f
    trigger:
      platform: event
      event_type: system_log_event
      event_data:
        level: ERROR
    mode: parallel
    max: 50
    action:
      - service: counter.increment
        entity_id: counter.syslog_errors

  - alias: "HASS: WARNINGs in System Log - Counter"
    id: acdf3489-b611-445c-bd24-2efc9c431124
    trigger:
      platform: event
      event_type: system_log_event
      event_data:
        level: WARNING
    mode: parallel
    max: 50
    action:
      - service: counter.increment
        entity_id: counter.syslog_warnings
