#################################################################
#                                                               #
#                            Unifi                              #
#                                                               #
#################################################################
automation:
  - alias: "Network: New device connected"
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.admins
        data:
          title: "Network Monitor"
          message: "There has been a new device detected on the network."

  - alias: "Network: WAN Status Change Notification"
    trigger:
      - platform: state
        entity_id: binary_sensor.wan
        for:
          hours: 0
          minutes: 2
          seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.allow_notifications
        state: "on"
    action:
      - choose:
          conditions:
            - condition: state
              entity_id: binary_sensor.wan
              state: "on"
          sequence:
            - service: persistent_notification.create
              data:
                title: Monitor
                message: "Internet access is back up"
                notification_id: internet_monitor
            - service: notify.admins
              data:
                title: Monitor
                message: "Internet access is back up"
            - delay: 120
            - service: persistent_notification.dismiss
              data:
                notification_id: unavailable_entities
        default:
          - service: persistent_notification.create
            data:
              title: Monitor
              message: "Internet access is down"
              notification_id: internet_monitor
          - service: notify.admins
            data:
              title: Monitor
              message: "Internet access is down"

binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: WAN
    scan_interval: 60

  - platform: ping
    host: 192.168.10.1
    name: Gateway
    scan_interval: 60

sensor:
  - platform: template
    sensors:
      internet_mb_downloaded:
        friendly_name: "Internet Download"
        unit_of_measurement: "MB"
        value_template: "{{ state_attr('binary_sensor.edgeos_interface_eth0', 'MBytes (Received)') }}"
      internet_mb_uploaded:
        value_template: "{{ state_attr('binary_sensor.edgeos_interface_eth0', 'MBytes (Sent)') }}"
        unit_of_measurement: "MB"

utility_meter:
  daily_internet_usage_in:
    source: sensor.internet_mb_downloaded
    cycle: daily
  daily_internet_usage_out:
    source: sensor.internet_mb_uploaded
    cycle: daily
