#################################################################
#                                                               #
#                            Alarm                              #
#                                                               #
#################################################################
alarm_control_panel:
  platform: manual
  name: Home Alarm
  arming_time: 30
  delay_time: 20
  trigger_time: 4
  disarmed:
      trigger_time: 0
  armed_home:
      arming_time: 0
      delay_time: 0
  armed_night:
      arming_time: 0
      delay_time: 0

group:
  alarm_sensors:
    - binary_sensor.unit2_nodeid_76_door_state
    - sensor.unit1_frontdoor_notification_access_control_door_state
    - binary_sensor.main_entrance_door_state
    - binary_sensor.unit1_bathroom_window_door_state #sensor.unit1_bathroom_window_alarm_access_control

  all_house_locks:
    - lock.frontdoor_lock
    - lock.backdoor_lock

input_boolean:
  panic_mode:
    name: Panic Mode
    initial: off
    icon: mdi:shield-outline

switch:
  - platform: template
    switches:
      panic_mode:
        value_template: "{{ is_state('input_boolean.panic_mode', 'on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: input_boolean.panic_mode
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: input_boolean.panic_mode

automation:
  - id: alarm_arm_home_at_night
    alias: 'Alarm: Arm Home at night'
    description: 'Arms the alarm, and locks the doors'
    initial_state: 'on'
    condition:
      - condition: state
        entity_id: group.household
        state: 'home'
    trigger:
      platform: time
      at: '22:00:00'
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.home_alarm
      - service: lock.lock
        entity_id: group.all_house_locks

  - id: alarm_arm_home_when_away
    alias: 'Alarm: Arm home when everyone is out'
    trigger:
      - entity_id: group.household
        platform: state
        from: 'home'
        to: 'away'
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.home_alarm  
      - service: notify.admins
        data:
          message: Alarm has been set to away.
          title: 'Home Alarm'

  - id: alarm_disarm_home
    alias: 'Alarm: Disarm alarm in the morning'
    
    trigger:
      platform: time
      at: "06:30:00"
    condition:
      - condition: state
        entity_id: group.household
        state: home
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.home_alarm

  - alias: Alarm - Panic Button On
    id: 'alarm_panic_button_on'
    description: 'Experimental: Panic button.'
    trigger:
      - platform: state
        entity_id: switch.panic_mode
        to: 'on'
    action:
      - service: notify.admins
        data:
          message: Panic Button Has Been Pressed!
          data:
            apns_headers:
            'apns-collapse-id': 'security-alarm'
            push:
              badge: 0
              category: "alarm"
              sound:
                name: default
                critical: 1
                volume: 1.0

          ##########################################################
          ## Panic Button Off
          ##########################################################

  - alias: Alarm - Panic Button Off
    id: 'alarm_panic_button_off'
    trigger:
      - platform: state
        entity_id: switch.panic_mode
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id:
          - switch.siren

          ##########################################################
          ## Panic Button Auto Off
          ##########################################################

  - alias: Alarm - Panic Button Auto Off
    id: 'alarm_panic_button_auto_off'
    trigger:
      - platform: state
        entity_id: switch.panic_mode
        to: 'on'
        for:
          hours: 0
          minutes: 2
          seconds: 0
    action:
      - service: switch.turn_off
        entity_id:
          - switch.siren