#################################################################
#                                                               #
#                        Sensor Checks                          #
#                                                               #
#################################################################
# Inspired by: https://blog.swakes.co.uk/home-assistant-system-dashboard/

group:
  dws_sensors:
    # Contact
    - binary_sensor.bathroom_window_home_security_tampering_product_cover_removed
    - binary_sensor.frontdoor_access_control_window_door_is_open
    - binary_sensor.main_entrance_access_control_window_door_is_open
    - binary_sensor.backdoor_access_control_window_door_is_open
    - binary_sensor.bedroom_window_access_control_window_door_is_open
    - binary_sensor.basement_door_access_control_window_door_is_open
    # Motion
    - binary_sensor.frontdoor_motion_home_security_motion_detection
    - binary_sensor.motion_living_room_home_security_motion_detection
    - binary_sensor.motion_bathroom_home_security_motion_detection
    - binary_sensor.motion_bedroom1_home_security_motion_detection
    - binary_sensor.motion_bathroom2_home_security_motion_detection
    - lock.frontdoor
    - lock.backdoor

sensor:
  - platform: template
    sensors:
      dws_sensors_online:
        value_template: >-
          {% set t = strptime(((now().timestamp() - 780) | timestamp_utc) ~ '+00:00', '%Y-%m-%d %H:%M:%S%z') %}
          {{
            expand('group.dws_sensors')
            | selectattr('last_changed', '<=' , t)
            | map(attribute='name')
            | list
            | count
          }}

      dws_sensor_check_status_count:
        icon_template: "mdi:door-open"
        friendly_name: DWS Sensors Count
        unit_of_measurement: count
        value_template: >-
          {{ expand('group.dws_sensors') | count }}

      dws_sensor_check_status_percent:
        entity_id:
          - sensor.dws_sensors_online
          - sensor.dws_sensor_check_status_count
        friendly_name: DWS Sensors Online
        icon_template: "mdi:door-open"
        unit_of_measurement: "%"
        value_template: >-
          {{ '%0.1f' | format(states('sensor.dws_sensors_online')|float / states('sensor.dws_sensor_check_status_count')|float * 100.0) }}

      dws_sensor_check_status:
        entity_id:
          - sensor.dws_sensor_check_status_percent
        friendly_name: DWS Sensors Online
        icon_template: "mdi:door-open"
        value_template: >-
          {{ states('sensor.dws_sensors_online') -}}/{{-  states('sensor.dws_sensor_check_status_count') -}}
