#################################################################
#                                                               #
#                            Unifi                              #
#                                                               #
#################################################################
automation:
  - alias: "New device connected"
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.admins
        data:
          title: 'Network Monitor'
          message: 'There has been a new device detected on the network.'

  - alias: Network - WAN Down Notification
    trigger:
      - platform: state
        entity_id: binary_sensor.wan
        to: 'off'
        for:
          hours: 0
          minutes: 1
          seconds: 0
    # condition:
    #   - condition: state
    #     entity_id: input_boolean.disable_notifications
    #     state: 'off'
    action:
      - service: persistent_notification.create
        data:
          message: "Internet Down"
          title: "WAN"
          notification_id: "1"

  - alias: Network - WAN Up Notification
    trigger:
      - platform: state
        entity_id: binary_sensor.wan
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 1
          seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.disable_notifications
        state: 'off'
    action:
      - service: persistent_notification.create
        data:
          message: "Internet Up"
          title: "WAN"
          notification_id: "1"

## Bandwidth Monitoring
input_number:
  wan_traffic_delta_in:
    min: 0
    max: 4294967295
  wan_traffic_delta_out:
    min: 0
    max: 4294967295

utility_meter:
  daily_internet_usage_in:
    source: sensor.internet_mb_downloaded
    cycle: daily
  daily_internet_usage_out:
    source: sensor.internet_mb_uploaded
    cycle: daily
  monthly_internet_usage_in:
    source: sensor.internet_mb_downloaded
    cycle: monthly
  monthly_internet_usage_out:
    source: sensor.internet_mb_uploaded
    cycle: monthly

sensor:
  - platform: template
    sensors:
      internet_mb_downloaded:
        friendly_name: "Internet Download"
        unit_of_measurement: 'MB'
        value_template: "{{ state_attr('binary_sensor.edgeos_interface_eth0', 'MBytes (Received)') }}"
      internet_mb_uploaded:
        value_template: "{{ state_attr('binary_sensor.edgeos_interface_eth0', 'MBytes (Sent)') }}"
        unit_of_measurement: 'MB'

      internet_usage_in:
        value_template: "{{ ((state_attr('binary_sensor.edgeos_interface_eth0','MBytes/ps (Received)')  | float)) | round(3) }}"
        unit_of_measurement: 'MB'
      internet_usage_out:
        value_template: "{{ ((state_attr('binary_sensor.edgeos_interface_eth0','MBytes/ps (Sent)')  | float)) | round(3) }}"
        unit_of_measurement: 'MB'
